### ISSUE TITLE
Why is it only a demo container?

### ISSUE THREAD

**Issue by fia5000** [passbolt/passbolt_docker#1]
It would be great if this could be scaled to be an actual method to deploy passbolt. I know for a fact that for my team, this would be allowed to be run as a docker container due to the siloing benefit of docker but not in its current recommended installation form - which is to run node.js on a webserver with other applications.

What are the drawbacks of using this in docker for production if an external database container is provided?

**Comment by kevinmuller** [comment]
Hi @fia5000,

In its current form, you don't need to run node.js on your webserver to use passbolt. Node.js is only required if you want to develop on passbolt and update some libraries, or if you want to run the passbolt client (currently in node.js, but will probably add some other languages later).

Regarding the drawbacks of using this container in production if an external database container is provided, this docker container has been designed more for development / demo purpose than for production. It has not been properly audited, nor tested for a production environment. In principle you could do it, but I would advise against it at least for the time being, until it has been reviewed in depth.

We aim to provide a production container very soon though. We'll keep you posted.

**Comment by fia5000** [comment]
@kevinmuller Thanks. I'll keep an eye on when you guys release a production ready docker image.

**Comment by JohannesRudolph** [comment]
Has any progress been made on a production container/docker-compose?

**Comment by stripthis** [comment]
Hi @JohannesRudolph,

This issue is in our backlog but no progress have been made. Currently we are working on the Chrome plugin and test suite optimization. We are in discussion to add a sysops to the team, but bear in mind that we are self-funded, so things do not always move as quickly as we wish.

Thank you for your interest,

**Comment by DerDummePunkt** [comment]
Hi there,

as far as a production ready stack goes for software in alpha status I think you might want to take a look at [our stack](https://github.com/Riodigital-de/passbolt-docker-compose).
With some tweaks this could also serve as a dev environment.

Happy new year everyone.

**Comment by mannp** [comment]
Is the docker still a demo only thing, as it appears to work ok.
