### ISSUE TITLE
Docker build fails with alpine:latest

### ISSUE THREAD

**Issue by vanton1** [passbolt/passbolt_docker#10]
Alpine Linux 3.6 doesn't include php5-memcache in their APKs, so build fails. I managed to built it with alpine:3.5 as base image but we need to decide if we'll support alpine 3.6 and newer and what changes on the packages are necessary.

**Comment by dlen** [comment]
Hi @vanton1, thanks for using passbolt!
Thanks for pointing out this issue. This scenario opens a discussion on how is passbolt going to manage alpine linux base image versions. We are working on automating the whole docker image testing and building. However, this won't happen in the short term, so in the mean time will dig on supporting alpine3.6 ASAP and fix passbolt image to alpine:3.6 to avoid situations like the one you described.

**Comment by dlen** [comment]
Hello again @vanton1 as a workaround we pinned alpine version to 3.5.
Thanks for your feedback again!
