### ISSUE TITLE
Unable to load a jpeg image as avatar.

### ISSUE THREAD

**Issue by dlen** [passbolt/passbolt_docker#100]
### What you did :memo:
docker-compose up using passbolt_docker provided docker-compose.yml
create an admin user
log into passbolt backend, update avatar image with a jpeg file

### What happened :collision: :clipboard:
User profile avatar shows a broken link 

```2018-04-16 18:48:23 Error: Unable to open image /var/www/passbolt/tmp/image-processing/999329a0-0320-4a95-9269-106187495e62
2018-04-16 18:48:23 Error: Unable to open image /var/www/passbolt/tmp/image-processing/999329a0-0320-4a95-9269-106187495e62
2018-04-16 18:48:23 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/img/public/images/Avatar/67/24/44/6472ffbbbca5443a86d30612f5c83b4d/6472ffbbbca5443a86d
30612f5c83b4d.65a0ba70.jpeg" could not be found.
Request URL: /img/public/images/Avatar/67/24/44/6472ffbbbca5443a86d30612f5c83b4d/6472ffbbbca5443a86d30612f5c83b4d.65a0ba70.jpeg
Referer URL: https://passbolt.local/
2018-04-16 18:48:23 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/img/public/images/Avatar/67/24/44/6472ffbbbca5443a86d30612f5c83b4d/6472ffbbbca5443a86d
30612f5c83b4d.a99472d5.jpeg" could not be found.
Request URL: /img/public/images/Avatar/67/24/44/6472ffbbbca5443a86d30612f5c83b4d/6472ffbbbca5443a86d30612f5c83b4d.a99472d5.jpeg
Referer URL: https://passbolt.local/
```
### What you expected to happen
See the just uploaded image

This issue refers to: https://github.com/passbolt/passbolt_api/issues/245

**Comment by dipeshm01** [comment]
has there been any update on the profile image issue of passbolt - it seems the profile image of an user is set correctly first time but after sometime same user finds his profile image to be broken - this is a very irritating issue - can anyone tell me the solution please... thanks in advance...

**Comment by dlen** [comment]
Hi @dipeshm01 this issue has been fixed almost a year ago.
Maybe what you experience is a lack of persistence on the avatars directory?
