### ISSUE TITLE
cron EmailQueue.sender job fails if db password contains certain characters

### ISSUE THREAD

**Issue by kissge** [passbolt/passbolt_docker#105]
Moved from https://github.com/passbolt/passbolt_api/issues/254.

* Passbolt Version: 2.0.7 (latest on Docker version as of now)
* Platform and Target:
  - Operating system: Docker on Amazon Linux 2 (2017.12) LTS Release Candidate
  - PHP: PHP 7.2.5 (cli) (built: May  5 2018 00:31:05) ( NTS )
  - Web server: nginx/1.10.3
  - Database server: 10.1.31-MariaDB MariaDB Server

### What you did :memo:
1. Configure Passbolt properly, with `DATASOURCES_DEFAULT_PASSWORD='y$ybDzq5C#Oq=?,(=L2vR,N6GpVJFlDf'`
2. Start account recovery

### What happened :collision: :clipboard:
No mail gets delivered.

Inspected DB and found `email_queue` filled with unsent items.
This means DB config is right.
Then I checked `/var/log/cron.log` and it contained lots of copies of the following line:

    Exception: SQLSTATE[HY000] [1045] Access denied for user '*******'@'*******' (using password: YES) in [/var/www/passbolt/vendor/cakephp/cakephp/src/Database/Driver/PDODriverTrait.php, line 48] 

This is strange. Then I changed DB password to alphabet-only word, and that worked (mails were sent).

### What you expected to happen
Recovery mail gets delivered

**Comment by dlen** [comment]
Hi @kissge !

Thanks for your issue report! I have reproduced it and it's an issue with the docker-entrypoint script at the time of exporting the environment variables for the cron job to work.
I would like to just heads up on the way you export the env variable with the quotes. If you are declaring the environment variables in an env file, as per the [docker documentation](https://docs.docker.com/compose/env-file/) "There is no special handling of quotation marks. This means that they are part of the VAL."

**Comment by kissge** [comment]
Actually I used `-e`  option in `docker run`, so I believe this is fine :)
Thanks anyway!
