### ISSUE TITLE
Website not accessible after running docker container

### ISSUE THREAD

**Issue by greatwitenorth** [passbolt/passbolt_docker#11]
I found that after running the following I was not able to access the container via it's ip (in my case 172.17.0.3):

```
docker run -e db_host=<mysql_container_ip> passbolt:1.4.0-alpine
```

This was due to the fact that my local computer is not able to access that network. When I forwarded port 443 to a unused port on my machine it started to work. This command ended up working for me (ex for unused_port, 9999):

```
docker run -e db_host=<mysql_container_ip> -p <unused_port>:443 passbolt:1.4.0-alpine
```

**Comment by dlen** [comment]
Hi @greatwitenorth thanks for your interest in passbolt!

Are you running GNU/linux as your host operating system or are you running on a different OS?

**Comment by greatwitenorth** [comment]
I'm using OS X and DOcker Community Edition Version 17.03.1-ce-mac12 (17661)

**Comment by dlen** [comment]
Hi @greatwitenorth thanks for the information. As I was suspecting you are using MacOS on your host, therefore you have to forward the ports.
It is a known limitation on MacOS systems: https://docs.docker.com/docker-for-mac/networking/#per-container-ip-addressing-is-not-possible
So yes, you are right. Thanks for pointing this out we didn't mention this scenario on the documentation but we will add it!
