### ISSUE TITLE
Wrong URLs when using nginx reverse proxy

### ISSUE THREAD

**Issue by mkohns** [passbolt/passbolt_docker#113]
I studied #82, #85, #82, #76 in order to get the following setup running:

-> nginx reverse proxy with SSL Offloading
-> location on www.example.com/passbolt

Therefor I stripped down nginx conf.d/default.conf

```
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
server {
        listen 443 ssl;
        access_log /var/log/nginx/access.log vhost;
        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.insecure.key;
   location /passbolt/ {
        rewrite /passbolt/(.*) /$1 break;
        proxy_pass http://passbolt:80;
   }
}
```

This is the snippet from passbolt.env

```
APP_FULL_BASE_URL=https://www.example.com/passbolt
PASSBOLT_REGISTRATION_PUBLIC=true
PASSBOLT_SSL_FORCE=false
```

I am using docker image passbolt/passbolt:2.4.0-debian, ID 90d6efc6f1bd, 

Error Description
-> Page loads and looks normal without errors in debug console
-> Page Header, Link "home" points to https://www.example.com, This is wrong. I assume https://www.example.com/passbolt
-> Page Header, Link "register" points to https://www.example.com/user/register, This is wrong. I assume https://www.example.com/passbolt/user/register
-> Page Header, Link "login" points to https://www.example.com/auth/login, This is wrong. I assume https://www.example.com/passbolt/auth/login
-> Page Body, All other links are fine pointing to either
https://www.example.com/passbolt/register
https://www.example.com/passbolt/recover
-> on register Page, after filling in name and mail, the button "register" leads to https://www.example.com/users/register. This is wrong. I assume https://www.example.com/passbolt/users/register
-> on register Page,  the link "already member" leads to https://www.example.com/login This is wrong. I assume https://www.example.com/passbolt/auth/login

Seems like some links are fine and respect the APP_FULL_BASE_URL, others do not.
Any ideas what I do wrong?

**Comment by mkohns** [comment]
Just to mention: I also did the respective hints from this post, without success:
https://community.passbolt.com/t/installing-passbolt-under-https-myurl-passbolt/483/4

**Comment by dlen** [comment]
Hi @mkohns ,

There are few threads in the passbolt community forum about using passbolt on a sudirectory even some open issues on passbolt_api repo: https://github.com/passbolt/passbolt_api/issues/252
Currently subdirectories it is not well supported. I suggest you to keep watching the above mentioned issue to keep track of the progress.
