### ISSUE TITLE
Bind for 127.0.0.1:3306 failed: port is already allocated

### ISSUE THREAD

**Issue by LeoK80** [passbolt/passbolt_docker#115]
### What you did :memo:
Explain what you did, steps to reproduce your issue, here.
I ran `docker-compose -f docker-compose.yml up`

### What happened :collision: :clipboard:
Provide information such as log outputs in this section showing what is
happening.

It seems to consistently spit out this error:

> Creating network "passbolt_docker_default" with the default driver
> Creating passbolt_docker_db_1 ... error
> 
> ERROR: for passbolt_docker_db_1  Cannot start service db: driver failed programming external connectivity on endpoint passbolt_docker_db_1 (fe78d19446a71f15fbc17f9e50514b1a158973f74391228f79a42e8210b13d31): Error starting userland proxy: Bind for 127.0.0.1:3306 failed: port is already allocated
> 
> ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint passbolt_docker_db_1 (fe78d19446a71f15fbc17f9e50514b1a158973f74391228f79a42e8210b13d31): Error starting userland proxy: Bind for 127.0.0.1:3306 failed: port is already allocated
> ERROR: Encountered errors while bringing up the project

### What you expected to happen
Explain what is the expected behaviour.

I expect both the Mysql/mariadb and passbolt containers to start up successfully

### What I did to fix it:

I changed the Mysql ports entry in the `docker-compose.yml` to read:
`ports:
      - 3306`
instead of 
`ports:
      - "127.0.0.1:3306:3306"`

**Comment by dlen** [comment]
Hi @LeoK80 

Seems like you are using the hosts port 3306, is that correct?

**Comment by dlen** [comment]
I will try to reproduce on macos @LeoK80 and come back to you!

**Comment by dlen** [comment]
Hi again @LeoK80 

Sorry for the delay. I have been trying to reproduce your issue on MacOS without success. The default docker-compose.yml works fine as it is.

I'm closing this issue but feel free to reopen if you have more information on how to reproduce it.

**Comment by Calhoun-z** [comment]
Had the same issue on a centos 7 vm with a much less helpful error while following the passbolt guide on installing with docker compose.

"cannot start service db: Unkown runtime specified docker-runc"

**Comment by garrettboone** [comment]
@Calhoun-z For help with installation issues, please post on the [forum ](https://community.passbolt.com/)thanks.
