### ISSUE TITLE
Using mail server with self-signed certificates

### ISSUE THREAD

**Issue by mseefeldt** [passbolt/passbolt_docker#116]
I use the Passbolt docker image and it works fine.
When i try to setup the e-mail sending, i run into a problem:

Whenever i try to test the sending with 
> ./bin/cake passbolt send_test_email -r "test@address.com"

i get the following error message:

```
Warning Error: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in [/var/www/passbolt/vendor/cakephp/cakephp/src/Network/Socket.php, line 473]

2018-11-13 12:50:38 Warning: Warning (2): stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in [/var/www/passbolt/vendor/cakephp/cakephp/src/Network/Socket.php, line 473]
```

I know that this is connected to the self-signed certificates/TLS and PHP checking the validity
of the TLS certificates, but how to get rid of it?

Changing the configuration files inside the container is no option since those changes disappear
when i upgrade to a new version.

Any help is appreciated!

Thanks in advance,
Marc

**Comment by dlen** [comment]
Hi!

Sorry for the delay! 
To use self signed you have to disable the SSL certificate peer. You could try to configure php engine to not verify SSL certs: http://php.net/manual/en/context.ssl.php (Not tested)
For that you will have to mount on the container a configuration file in /usr/local/etc/php-fpm.d

**Comment by mseefeldt** [comment]
Hi Diego,

thanks a lot for the answer.
I would like to try your proposed solution but i am stuck a bit in the execution of the solution.

I already figured out which options to set:

```
verify_peer: false
verify_peer_name: false
allow_self_signed: true
```

From the php-fpm configuration i got the name of the configuration file
(e.g. allowSelfSigned.conf). As far as i understood, the options for the stream in
php are changed by using the additional configuration file.

Here is the point where i am stuck:
I don't know the syntax to use in the configuration file in order to apply the settings.
(PHP is not my area of expertise..., i work more in the JavaScript/Node.js realm)

Many thanks in advance,
Marc

**Comment by mackcoding** [comment]
I am also having this exact issue. Where do we put the allow_self_signed? Is that in the INI file?

**Comment by dlen** [comment]
Regarding this issue and for people reaching here looking for solutions:

Add the following snippet to your 'EmailTransport' => 'default' section on the config/app.php file:
```
context => [  
  'ssl' => [
    'verify_peer' => false,
    'verify_peer_name' => false,
    'allow_self_signed' => true
  ]
]
```

**Comment by secresearch-rg** [comment]
Hi!

Just figured out how to give CakePHP / Passbolt an exact path to the self-signed CA it should use to verify encrypted SMTP connections.  On the web I could only find suggestions that involved disabling TLS verification for self-signed certs, which is undesirable.

Inside your Passbolt app config file where SMTP settings are located (hostname, creds, ports), you have to use this option to specify the file path to the CA file (I used a PEM certificate format):

```
'EmailTransport' => [
  'default' => [
    ...    
    'ssl_cafile' => '/usr/local/share/ca-certificates/CustomCA.crt',
    ...
],
```

Found that while reading the relevant source code of CakePHP, namely [this](https://github.com/cakephp/cakephp/blob/7ca040245f9c9c5685fc101e6da2d9aa5d3d483f/src/Http/Client/Adapter/Stream.php)  file.

I used that successfully with SMTP over port 465 (smtps).
Maybe that will help someone!
