### ISSUE TITLE
Mounting the GPG keys

### ISSUE THREAD

**Issue by cypherkey** [passbolt/passbolt_docker#12]
I want to persist the GPG keys. I created the container mounting the private and public key using -v as per the README. For example:
```
docker run -e db_host=172.17.0.1 -e db_database=passbolt -e db_pass=XXXXXX \
    -v /pub/passbolt/private.asc:/var/www/passbolt/app/Config/gpg/serverkey.private.asc \
    -v /pub/passbolt/public.asc:/var/www/passbolt/app/Config/gpg/serverkey.asc \
    --name passbolt -p 8082:80 passbolt/passbolt
```
If the file /pub/passbolt/public.asc (or private) don't exist in /pub on the host, docker creates a directory (eg /pub/passbolt/public.asc/) and not a blank file and the container obviously fails to start. 

If I generate a key on the host, export it and put it in /pub/passbolt, the container starts up the first time. The second time it doesn't start because docker-entrypoint.sh attempts to re-import the private key. This causes an error and causes the container to stop. I fixed this by changing the entrypoint to check to see if a key exists in the keystore:
```
numkeys=`su -m -c "$gpg --list-keys | egrep '^pub'" -ls /bin/bash nginx | wc -l`
if [ ${numkeys} = "0" ]; then
  su -m -c "$gpg --batch --import $gpg_private_key" -ls /bin/bash nginx
fi
```
This isn't the best way to detect whether the key already exists, but it worked to determine this was the problem. GPG doesn't seem to cause a fatal error if you attempt to re-import the public key.

**Comment by dlen** [comment]
Hi @cypherkey!
Thanks for your feedback. Unfortunately as for your description I'm not able to reproduce your problem. If you only persist the .asc files the keyring should be empty when you launch the container. Importing the public and private keys every time should not be a problem but seems I'm missing something in the process you are following to obtain this error. Could you describe the whole process and the errors obtained?

**Comment by cypherkey** [comment]
The keyring is empty when the container is first run. If I stop the container and then start it, the keyring still has the keys and the init script will try and re-import them. I guess this could be mitigated by having docker delete the container when it stops (--rm). 

Here are my repo steps:
1) Create a persistence directory 
$ mkdir /pub/passbolt1
$ cd /pub/passbolt1

2) Put keys in directory
$ ls -l
total 8
-rw-rw-r-- 1 ada users 3553 Jun  1 02:25 private.asc
-rw-rw-r-- 1 ada users 1686 Jun  1 02:25 public.asc

3) Create the container mapping the files in to the container
$ docker run -d -e db_host=172.17.0.1 -e db_database=passbolt -e db_pass=XXXXXX \
    -e ssl=false \
    -v /pub/passbolt1/private.asc:/var/www/passbolt/app/Config/gpg/serverkey.private.asc \
    -v /pub/passbolt1/public.asc:/var/www/passbolt/app/Config/gpg/serverkey.asc \
    --name passbolt passbolt/passbolt

4) Check the logs. The container started
$ docker logs passbolt
Generating a 4096 bit RSA private key
.......................++
...........................++
writing new private key to '/etc/ssl/certs/certificate.key'
-----
Enjoy! ☮

5) Stop the container
$ docker stop passbolt
$ docker inspect passbolt | grep Status
            "Status": "exited",

6) Start the container and wait 10 seconds
$ docker start passbolt

7) Check the status of the container. It's stopped.
$ docker inspect passbolt | grep Status
            "Status": "exited",

8) Check the logs
$ docker logs passbolt
gpg: key FE85CB01: already in secret keyring
gpg: Total number processed: 1
gpg:       secret keys read: 1
gpg:  secret keys unchanged: 1

HTH

**Comment by dlen** [comment]
Thanks again for your feedback @cypherkey 
We have solved the issue in a slightly different way as the one you proposed. Instead of checking for the number of keys we check if that keyid from the .asc file exists.
If you find any other issue please let us know!
