### ISSUE TITLE
DiceBaby!

### ISSUE THREAD

**Issue by ccastleberry** [passbolt/passbolt_docker#120]
## IMPORTANT :hand: :point_up: Please read

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

If you still want to report a bug please take a look first on the other open/closed tickets to avoid duplicating issues.

### How to provide a good issue report:
- Provide all the information you can collect about your problem
- Provide log outputs from (some examples follow):
  - /var/www/passbolt/tmp/logs/error.log
  - /var/log/nginx/error.log
  - curl -vvvLk http://passboltdomain
  - Any other sources you might think will help to solve the problem

### What you did :memo:
Explain what you did, steps to reproduce your issue, here.

### What happened :collision: :clipboard:
Provide information such as log outputs in this section showing what is
happening.

### What you expected to happen
Explain what is the expected behaviour.

**Comment by dlen** [comment]
Please add a description of the issue you are experiencing with a proper description and reopen if necessary.
