### ISSUE TITLE
Migrations broken when updating from 2.4.0 (non docker) to 2.10.0 (with docker)

### ISSUE THREAD

**Issue by tostiheld** [passbolt/passbolt_docker#128]
### What you did :memo:
Update a non docker installation from 2.4.0 to 2.10.0 with docker

### What happened :collision: :clipboard:
Migrations no longer run (exception is thrown about a table that already exists)

### What you expected to happen
Migrations do run

Log: [passbolt.log](https://github.com/passbolt/passbolt_docker/files/3414710/passbolt.log)

**Comment by tostiheld** [comment]
It is worth nothing that the installation still seems to work fine though, for several months now.

**Comment by stripthis** [comment]
Hi @tostiheld is this issue specific to docker? As in you are able to upgrade normally if using "non-docker" update procedure? I double checked and the table that is creating an issue was introduced in 2.8 and was not present in 2.4. 

I'm having issues understanding what kind of state your database is at the moment, can you explain in more details what you did and in which order.

**Comment by tostiheld** [comment]
I don't know if the issue is specific to docker. Maybe it is caused by the way the docker image handles migrations? Just a guess.

I had an old passbolt installation directly behind an nginx instance using a mariadb database. I basically configured a docker image the same way as my old installation was configured. Then I started the docker container. The mentioned exception is thrown, but the installation continues to work fine. I imagine migrations not running might get problematic at some point, though.

Concerning the state of my database: I think the schemas still look like they looked in version 2.4

**Comment by dlen** [comment]
Closing as stale if it persists please feel free to reopen
