### ISSUE TITLE
Running passbolt behind a reverse proxy

### ISSUE THREAD

**Issue by cypherkey** [passbolt/passbolt_docker#13]
I've setup the docker container. I run my docker containers behind an apache reverse proxy so that I can access them from the outside. When I try to access it as https://myserver.mydomain.com/passbolt/auth/login, the CSS and JS return errors. The issue appears to be that the path to the css and js files are an absolute path and not relative. 

```
<link rel="stylesheet" type="text/css" href="/css/login.min.css"/>
<script type="text/javascript" src="/js/lib/modernizr/modernizr-custom.min.js"></script>
<script type="text/javascript" src="/js/lib/jquery/dist/jquery.js"></script>
```

I've tried messing with the App.fullBaseUrl and App.baseUrl entries in core.php and it doesn't seem to affect it.  Is it possible to prepend those path with some value?

**Comment by kevinmuller** [comment]
Hi @cypherkey 

You should be able to fix this by uncommenting and changing the value of the configuration rules below in app/Config/core.php:

```
/**
 * Web path to the CSS files directory under webroot.
 * If not set defaults to 'css/'
 */
	//Configure::write('App.cssBaseUrl', 'css/');

/**
 * Web path to the js files directory under webroot.
 * If not set defaults to 'js/'
 */
	//Configure::write('App.jsBaseUrl', 'js/');
```

So in your case that would be: 
```
Configure::write('App.cssBaseUrl', 'passbolt/css/');
Configure::write('App.jsBaseUrl', 'passbolt/js/');
```

Let me know if that works.

Kevin

**Comment by cypherkey** [comment]
It looks like another person is having the same issue and opened issue 81 under passbolt_api. My suggestion is that once that is resolved, options are exposed as docker env vars.

**Comment by dlen** [comment]
I'm closing this issue,  we will keep track of https://github.com/passbolt/passbolt_api/issues/81 When the fix is public we will consider the strategy you proposed @cypherkey. Thanks again for your contribution!
