### ISSUE TITLE
2.11.0-debian docker image does not chown

### ISSUE THREAD

**Issue by bartekbrak** [passbolt/passbolt_docker#131]
### What you did :memo:
```
# docker run --rm -it passbolt/passbolt:2.11.0-debian ls -l /home/
total 4
drwxr-xr-x 2 root root 4096 Aug  8 14:45 www-data
```
notice who owns the directory, `root`.

### What happened :collision: :clipboard:
[Dockerfile states](https://github.com/passbolt/passbolt_docker/blob/v2.11.0/Dockerfile#L43-L44):
```
    && mkdir /home/www-data \
    && chown -R www-data:www-data /home/www-data \
```
but home directory is still owned by `root`. Therefore `docker-compose up`:
```
passbolt_1  | gpg: Fatal: can't create directory '/home/www-data/.gnupg': Permission denied
```
I do not understand how the image was built but suppose that it was not built from tag `v2.11.0`. When I built it from that tag I got a correct but different to yours effect:
```
# docker run --rm -it passbolt-mine ls -l /home/
drwxr-xr-x 2 www-data www-data 4096 Sep 21 09:41 www-data
```
### What you expected to happen
I expect `/home/www-data` to be owned by `www-data`

**Comment by dlen** [comment]
Hi @bartekbrak!

Thanks for your report. I'm however unable to reproduce your situation:

```docker run --rm -it passbolt/passbolt:2.11.0-debian bash                                                                                                                   
Unable to find image 'passbolt/passbolt:2.11.0-debian' locally
2.11.0-debian: Pulling from passbolt/passbolt
Digest: sha256:9a82cc389f6615b3ce90bc00f2592fd42d2b4f68439a3b16cacf65ed2c75e39b
Status: Downloaded newer image for passbolt/passbolt:2.11.0-debian
root@ea242be222bc:/var/www/passbolt# cd /home/
root@ea242be222bc:/home# ls -las
total 12
4 drwxr-xr-x 1 root     root     4096 Sep 17 13:06 .
4 drwxr-xr-x 1 root     root     4096 Sep 21 10:53 ..
4 drwxr-xr-x 2 www-data www-data 4096 Sep 17 13:06 www-data
```

**Comment by bartekbrak** [comment]
Not sure what happened but I cannot reproduce any more after I deleted the image and pulled again, I have verified on 3 different servers and the issue is gone. 

Thank you for your time, seems the error was on my side.
