### ISSUE TITLE
SMTP ehlo name

### ISSUE THREAD

**Issue by dg-otrs** [passbolt/passbolt_docker#132]
Hey,

I try to setup smtp mail send and my test fails (x=for data sec):
root@4d8056d6dba2:/var/www/passbolt# bin/cake passbolt send_test_email -r xx@xxx.com
Email configuration
---------------------------------------------------------------
Host: XXX.com
Port: 25
Username:
Password: *********
TLS: true

Sending email from: password@XXX.com
Sending email to: xx@XXX.com
---------------------------------------------------------------

Trace
[220] XXX.com ESMTP Postfix
**> EHLO localhost**
[250] XXX.com
[250] PIPELINING
[250] SIZE 51200000
[250] VRFY
[250] ETRN
[250] STARTTLS
[250] ENHANCEDSTATUSCODES
[250] 8BITMIME
[250] DSN
[250] SMTPUTF8
[250] CHUNKING
> STARTTLS
[220] 2.0.0 Ready to start TLS
> EHLO localhost
[250] XXX.com
[250] PIPELINING
[250] SIZE 51200000
[250] VRFY
[250] ETRN
[250] ENHANCEDSTATUSCODES
[250] 8BITMIME
[250] DSN
[250] SMTPUTF8
[250] CHUNKING
> MAIL FROM:<password@XXX.com>
[250] 2.1.0 Ok

A test email could not be sent.
**Error: SMTP Error: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname**

As you can see the problem is the fq hostname... our mail server does not allow such one. How to set the right host name?

Was not able to find it, is it docker related or passbolt?

Cheers

Dennis

**Comment by dlen** [comment]
Sorry for the delay here. 
@remy helped me with this one and found that you might need to define the env variable: `EMAIL_TRANSPORT_DEFAULT_CLIENT` to point to a FQDN or IP address, whatever your SMTP server requires.

**Comment by dg-otrs** [comment]
Worked perfectly!
