### ISSUE TITLE
minor typo in CHANGELOG.md

### ISSUE THREAD

**Issue by squalou** [passbolt/passbolt_docker#144]
Hi,

nothing important,

just to mention two typos in :

https://github.com/passbolt/passbolt_docker/blob/master/CHANGELOG.md

* release date of 2.12.1 should be **2020**, not **2019** :)
* `Pasbsolt` instead of `Passbolt` ;-)

**Comment by stripthis** [comment]
Thanks for pointing this out it's fixed!
