### ISSUE TITLE
How to update the installation from 2.7.2 to  v2.12.1. 

### ISSUE THREAD

**Issue by AhmadAbuHashem** [passbolt/passbolt_docker#145]
I have no idea how to update the installation to higher version in docker. 
I am using docker-compose. Is there any guide to use to help me  step by step

**Comment by dlen** [comment]
Hi @AhmadAbuHashem , 
Thanks for your interest in passbolt. This question fits more our [community forum](https://community.passbolt.com) we try to keep the github issues for bugs. However I will describe the process for you:

You just need to backup the usual:
- Database
- Serverkeys
- Images (optional)

Follow this guide to make a passbolt backup: https://help.passbolt.com/hosting/backup

Once you have the above data backed up you can just change the container image you are running and the migrations will be automatically executed on boot. As you are using docker-compose you just need to change the passbolt version you are using on the docker-compose.yml
