### ISSUE TITLE
Unable to set up first account

### ISSUE THREAD

**Issue by vmsh0** [passbolt/passbolt_docker#147]
On a fresh Docker image, giving

`docker exec passbolt_passbolt_1 su -m -c "/var/www/passbolt/bin/cake passbolt register_user -u '[omitted]' -f '[omitted]' -l '[omitted]' -r admin" -s /bin/sh www-data`

results in a setup link being correctly generated; however, when trying it in the web browser, I'm presented with the following screen:
![image](https://user-images.githubusercontent.com/1955497/84262043-30d6b480-ab1d-11ea-87e5-646c2eb8927f.png)

The provided debug info is:
```
{
  "setup": {
    "stepId": "",
    "stepsHistory": "",
    "user": {
      "username": "[omitted]",
      "firstname": "[omitted]",
      "lastname": "[omitted]",
      "id": "a9744e4a-2169-4239-9eff-c29d15b537de"
    },
    "key": {},
    "settings": {
      "token": "",
      "domain": "",
      "securityToken": {},
      "armoredServerKey": ""
    }
  },
  "additional": {
    "settings": {
      "token": "98099140-01ff-4565-b997-7faa1efa5364",
      "domain": "https://passbolt:5600",
      "workflow": "install"
    },
    "user": {
      "username": "[omitted]",
      "firstname": "[omitted]",
      "lastname": "[omitted]",
      "id": "a9744e4a-2169-4239-9eff-c29d15b537de"
    }
  }
}
```

I tried the same exact process twice on fresh Docker containers with fresh volumes with no luck. I tried once with DEBUG=1 and once without, with identical results.

/var/log/nginx/error.log and /var/www/passbolt/logs/error.log are both empty (the second one didn't even get created the second time, as the first time it logged some unrelated route errors, while it didn't have a chance to do it the second time).

These are the env I use for the containers:
```
ele-docker@VSRV-DOCKER:~/passbolt$ cat env/mysql.env
MYSQL_ALLOW_EMPTY_PASSWORD=1
MYSQL_DATABASE=passbolt
MYSQL_USER=passbolt
MYSQL_PASSWORD=passbolt

ele-docker@VSRV-DOCKER:~/passbolt$ cat env/passbolt.env
DATASOURCES_DEFAULT_HOST=db
DATASOURCES_DEFAULT_PASSWORD=passbolt
DATASOURCES_DEFAULT_USERNAME=passbolt
DATASOURCES_DEFAULT_DATABASE=passbolt
APP_FULL_BASE_URL=https://passbolt:5600
DEBUG=1
```

My exact steps are as follows:
```
docker-compose up
<verify from the output that database tables are created and migrations applied>
<Ctrl-C> (wait for graceful stop)
docker-compose up -d
docker-compose logs (verify that passbolt has started)
docker exec passbolt_passbolt_1 su -m -c "/var/www/passbolt/bin/cake passbolt register_user -u '[omitted]' -f '[omitted]' -l '[omitted]' -r admin" -s /bin/sh www-data
<copy the URL and paste it in a web browser running the extension>
```

I have also posted this on the forum: https://community.passbolt.com/t/installing-on-docker/2812/3
And this seems to be related (or even identical) to [passbolt_api#41](https://github.com/passbolt/passbolt_api/issues/41)

**Comment by stripthis** [comment]
Hello, 

Please do not create double entries on github for installation issues.
This place is reserved for bugs. Thanks,
