### ISSUE TITLE
Alternative way to setup the root user (Initial setup)

### ISSUE THREAD

**Issue by asakapab0i** [passbolt/passbolt_docker#149]
### What you did :memo:
I setup the passbolt docker using AWS Fargate, the problem is Fargate is a managed container infrastructure and it means that I cannot login to the docker container and execute the initial admin user registration.

### What happened :collision: :clipboard:
There is no way for me to setup the admin user because there is no way to inject an init script right after the container starts up.

### What you expected to happen
During the initial setup of the passbolt application, the setup should happen in the UI not in the docker / server.

**Comment by dlen** [comment]
Hi @asakapab0i !

Thanks for your report! It has been a while for me I don't use fargate but won't it be possible for you to run another passbolt container (on the side of the one you are running to serve the passbolt service) that just runs the first user registration? 
It would be kind of a one-off job container that just runs the registration command and exits providing in the output the registration link.

**Comment by asakapab0i** [comment]
Hi @dlen ,

Thanks for the quick response, yes we can run a one-off docker container and execute the script. 

Let me know what you have in mind in terms of injecting the registration script in another container.

**Comment by asakapab0i** [comment]
Hi @dlen ,

Thanks for the suggestion, I had to modify the docker-entry.sh and manually add the registration of the admin.

After the registration, I then created a new image with the registration line removed.

It's a tedious process but at least it works!!

I'm closing this issue now.

**Comment by HieronyM** [comment]
Sorry to comment on closed issue?

@asakapab0i 
Do you still have the modified docker-entry.sh and a new image with the registration line removed?
I'm also have this case where I need to run passbolt in Cloudrun.

Thank you

**Comment by asakapab0i** [comment]
> lso have this case where I need to run passbolt in Cloudrun.

Yup, I had to modify/revert it back again.

There's an alternative. You can now SSH to the container in fargate FYI.
