### ISSUE TITLE
Avatar upload won't work

### ISSUE THREAD

**Issue by ArtPixWebdesign** [passbolt/passbolt_docker#150]
Using the passbolt_docker, when I try to upload an image (jpg or png) to set an avatar,
I get a 500... : 
passbolt_1  | NOTICE: PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/passbolt/vendor/knplabs/gaufrette/src/Gaufrette/Util/Path.php on line 30
passbolt_1  | NOTICE: PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/passbolt/vendor/knplabs/gaufrette/src/Gaufrette/Util/Path.php on line 34
passbolt_1  | NOTICE: PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/passbolt/vendor/knplabs/gaufrette/src/Gaufrette/Util/Path.php on line 36
passbolt_1  | 2020/12/06 16:17:04 [error] 158#158: *51 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/passbolt/vendor/knplabs/gaufrette/src/Gaufrette/Util/Path.php on line 30PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/passbolt/vendor/knplabs/gaufrette/src/Gaufrette/Util/Path.php on line 34PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/passbolt/vendor/knplabs/gaufrette/src/Gaufrette/Util/Path.php on line 36" while reading response header from upstream, client: 172.20.0.1, server: , request: "POST /users/c2f8f4f7-41ad-49f1-b3f8-8023d9881c95.json?api-version=v2 HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8043", referrer: "https://mydomain.test/app/settings/profile"
passbolt_1  | 127.0.0.1 -  06/Dec/2020:16:17:04 +0000 "POST /index.php" 500

**Comment by dlen** [comment]
Hi @ArtPixWebdesign 

Thanks for your report. I can confirm the issue when uploading images with extension '.jpeg'. This is the entry on the error.log

```
2020-12-07 08:28:56 Error: [App\Error\Exception\ValidationException] Could not validate user data. (/var/www/passbolt/src/Controller/Users/UsersEditController.php:48)
Request URL: /users/d3609b4f-373c-4edf-a2e3-2ddaa2992e6f.json?api-version=v2
Referer URL: https://passbolt.local/app/settings/profile
```

**Comment by dlen** [comment]
Could you provide which version of the docker image are you using?

**Comment by ArtPixWebdesign** [comment]
passbolt/passbolt:2.13.5-debian

**Comment by dlen** [comment]
Closing as stale, feel free to reopen if still happens

**Comment by ArtPixWebdesign** [comment]
Well done ! This bug was fixed since several versions...
