### ISSUE TITLE
SSL e-mail issue

### ISSUE THREAD

**Issue by ArtPixWebdesign** [passbolt/passbolt_docker#151]
using docker passbolt/passbolt:2.13.5-debian
According to the documentation https://help.passbolt.com/configure/email/setup
I was unable to send e-mails over SSL with my provider (non-SSL was working well).

The debug : 
trying the send email test https://help.passbolt.com/faq/hosting/why-email-not-sent
inside the container, I saw that it was always trying with TLS and not SSL

The root cause : 
semms like the docker environnement variable EMAIL_TRANSPORT_DEFAULT_TLS=null
was not processed correctly in the container (eq true)

The solution : 
I had to edit the php file inside the running container (docker exec -it passbolt...)
`sed -i "s/'tls' => env('EMAIL_TRANSPORT_DEFAULT_TLS', null),/'tls' => null,/" /var/www/passbolt/config/app.php`
to make it work...

**Comment by garrettboone** [comment]
@ArtPixWebdesign Can you provide an example of your SSL environment variable settings that were not working?

**Comment by befocken** [comment]
I think I just had a similar issue.
Though it may be that I'm a little confused with the terminology.
Is the environment variable `EMAIL_TRANSPORT_DEFAULT_TLS` supposed to specify if an encryption is used at all, or just if TLS or SSL is used?
Like, the default value is `null`, does that mean, that the e-mails are sent unencrypted or are they just sent via SSL?

I think the documentation is not clear hear, as the description just says 'Set tls'.

**Comment by garrettboone** [comment]
@befocken In the [cakephp docs here](https://book.cakephp.org/4/en/core-libraries/email.html), it says that false will be "not TLS" and if SSL is desired, to include `ssl://` in the host field.

**Comment by almereyda** [comment]
It appears this can be closed.
