### ISSUE TITLE
Missing runtime dir for php-fpm

### ISSUE THREAD

**Issue by oyxnaut** [passbolt/passbolt_docker#154]
`passbolt/passbolt:3.0.0-pro@sha256:2f4280a66c4311aea11f09798906e338baf33024db10a8ccea9d08bb6e9248bd`, and `passbolt/passbolt:3.0.1-pro@sha256:2f4280a66c4311aea11f09798906e338baf33024db10a8ccea9d08bb6e9248bd` have a missing runtime dir error:
> ERROR: unable to bind listening socket for address '/run/php/php7.3-fpm.sock': No such file or directory (2)

This could be fixed in the Dockerfile by adding `RUN mkdir /run/php/ && chmod www-data:www-data /run/php/`, or in `docker-entrypoint.sh` by adding
```bash
if [ ! -d /run/php/ ]; then
  mkdir /run/php/
  chown www-data:www-data /run/php/
fi
```
just before the call to `exec /usr/bin/supervisord -n`.
I suppose putting the `mkdir` into the `RUN` layer in the `Dockerfile` makes more sense than in `docker-entrypoint.sh`, seeing that you're providing a rootless image, as well.

**Comment by dlen** [comment]
Hi @oyxnaut how are you launching the container? Are you using docker-compose? We have seen this in the past when /run is mounted on tmpfs

**Comment by oyxnaut** [comment]
Thank you. Removing
```yaml
tmpfs:
  - /run
 ```
did the trick. When we first deployed passbolt, we copied the docker-compose.yml from the repo, but we missed commit 5a8fd286befbd08658dce46102982b163ce61f3c.
