### ISSUE TITLE
Outdated Docker README

### ISSUE THREAD

**Issue by tmfksoft** [passbolt/passbolt_docker#155]
The README on the docker page @ https://hub.docker.com/r/passbolt/passbolt/ is outdated.
Other than the year showing as 2018 vs this repo showing 2021, the instructions on creating the first user are incorrect.

The command:
`$ docker exec passbolt su -m -c "/var/www/passbolt/bin/cake passbolt register_user -u your@email.com -f yourname -l surname -r admin" -s /bin/sh www-data`

Results in
`sh: 1: /var/www/passbolt/bin/cake: not found`

While the different command in this repos README performs as expected.

**Comment by dlen** [comment]
hi @tmfksoft !

Thanks for the heads up it has just been updated!
