### ISSUE TITLE
csv import not working

### ISSUE THREAD

**Issue by Gjonni** [passbolt/passbolt_docker#156]
## IMPORTANT :hand: :point_up: Please read

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

If you still want to report a bug please take a look first on the other open/closed tickets to avoid duplicating issues.

### How to provide a good issue report:
- Provide all the information you can collect about your problem
- Provide log outputs from (some examples follow):
  - /var/www/passbolt/tmp/logs/error.log
  - /var/log/nginx/error.log
  - curl -vvvLk http://passboltdomain
  - Any other sources you might think will help to solve the problem

### What you did :memo:
I have always used the import from csv and it has always worked correctly but since yesterday the generic error "not found" appears.
Seeing the log file I find
2021-03-04 09:52:20 Error: [Cake \ Routing \ Exception \ MissingRouteException] A route matching "/resource-types.json" could not be found. (/var/www/passbolt/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:216)
Request URL: /resource-types.json?api-version=v2

IMAGE: docker.io/passbolt/passbolt:2.13.5-debian
Can you help me understand the problem?

### What happened :collision: :clipboard:
![Schermata 2021-03-04 alle 10 52 26](https://user-images.githubusercontent.com/27830752/109945654-bfa4e600-7cd7-11eb-944c-e0925652a624.png)

### What you expected to happen
Upload password from csv

**Comment by stripthis** [comment]
@Gjonni  we're investigating the issue and come back to you.

**Comment by Gjonni** [comment]
Do you recommend updating it to version 3 (not-root)?

**Comment by Gjonni** [comment]
I upgraded to the passbolt / passbolt image version: 3.0.1-ce and now it works.
I would also like to switch to a not-root version .. tell me how to do it?

**Comment by alexfoo** [comment]
Hello,

I had the same error, but from exporting. Turns out there's a mismatch between the JS running in the passbolt chrome plugin that does support older (non-3.x) passbolt API.
Upgrading to passbolt 3.x fixed the problem for me. Just remember to also upgrade php (if less than 7.3).

Hope this helps someone!

**Comment by cedricalfonsi** [comment]
Fixed with v3.0.7
Feel free to reopen of the problem persists.
