### ISSUE TITLE
Import the password from the old Passbolt server export to the latest Passbolt server and the password is not displayed

### ISSUE THREAD

**Issue by chyff** [passbolt/passbolt_docker#157]
I installed the latest Passbolt database in another server and imported the database. The user exists, but the password cannot be seen. How to solve this problem?

**Comment by stripthis** [comment]
Hello,

As indicated in the issue template, please use the community forum for installation or upgrade issue, as this space is reserved for bugs:  https://community.passbolt.com/

Cheers,
