### ISSUE TITLE
Importing character set problems

### ISSUE THREAD

**Issue by chyff** [passbolt/passbolt_docker#158]
Hello, I created the user name and password on one server and exported them normally, but they were confused after importing them on another new server. When I input the Chinese user name on the new server, the display was normal
![image](https://user-images.githubusercontent.com/33062193/110290538-d9229680-8025-11eb-8e64-61e9768c0697.png)

**Comment by stripthis** [comment]
Hi @chyff this repository is for docker related issue. Can you post your issue again to https://github.com/passbolt/passbolt_browser_extension/ explaining which methods / steps you used to export and import. Maybe there is an issue with the file enconding on a specific format.
