### ISSUE TITLE
No cron to run EmailQueue.sender

### ISSUE THREAD

**Issue by cypherkey** [passbolt/passbolt_docker#16]
I checked the Dockerfile and the entry point script but I don't see where a crontab is setup to call the EmailQueue.sender script.

**Comment by dlen** [comment]
Thanks @cypherkey for your feedback again! We will dig into this issue to fix it in the following days.

**Comment by dlen** [comment]
Hi @cypherkey,
The docker container has been updated, new env variables have been added to manage the email settings and a cron job has been set up to check email queue.

Hopefully this solves this issue.
Thanks again for your contributions to passbolt!
