### ISSUE TITLE
Passbolt only displays blank page at setup

### ISSUE THREAD

**Issue by Gitoffomalawn** [passbolt/passbolt_docker#160]
I've followed the setup steps from the README to the letter (using the docker-compose file). When it comes to setting up the first (admin) user, the container generates a URL to navigate to for first user setup. I then navigate to this URL, leading me to a warning regarding the self-signed certificate. So far, so good.

After accepting the browser warning, I am greeted with a blank page instead of the Passbolt user setup wizard. I have tried the URL on 3 different browsers, all return a blank page. Currently, this means there is no way for me to set up Passbolt.

**Comment by stripthis** [comment]
Hello,

As indicated on the issue template, this space is reserved for bugs.
Please open a ticket on the community forum under installation issues, with all the requested information. 
https://community.passbolt.com/
