### ISSUE TITLE
/etc/passbolt/jwt does not exist

### ISSUE THREAD

**Issue by IDevJoe** [passbolt/passbolt_docker#169]
### Issue
- /etc/passbolt/jwt does not exist immediately

### What you did :memo:
- Initialized passbolt with PASSBOLT_PLUGINS_JWT_AUTHENTICATION_ENABLED=true

### What happened :collision: :clipboard:
![image](https://user-images.githubusercontent.com/11019048/146465352-04dcc3f7-62d2-4408-b142-4a2950180f8c.png)

The private key could not be written.

### What you expected to happen
The private key is written, and passbolt initializes correctly.

### Workaround
I modified the dockerfile and added `RUN mkdir /etc/passbolt/jwt && chown www-data:www-data /etc/passbolt/jwt`. Although this fixes the issue, I'm not entirely sure it's sufficient enough and could be fixed another way.

**Comment by AnatomicJC** [comment]
Hi @IDevJoe 👋 

Thanks for reporting this but as mobile application is still in beta and not enabled yet by default, this is why `/etc/passbolt/jwt` is not created in our docker image.

It will be on a future release.

Best regards,
