### ISSUE TITLE
Admin Passphrase not recognized

### ISSUE THREAD

**Issue by eliasbalasis** [passbolt/passbolt_docker#171]
### What I did :memo:
I followed the instructions at https://help.passbolt.com/hosting/install/ce/docker.html and I managed to successfully run the service and create the admin user.

I even received an activation e-mail, having configured e-mail delivery using EMAIL_TRANSPORT_DEFAULT_HOST, EMAIL_TRANSPORT_DEFAULT_PORT, EMAIL_DEFAULT_FROM, EMAIL_DEFAULT_FROM_NAME

I used the activation link to setup the admin user and kept in a safe place both the passphrase and the PGP key (recovery kit).

### What happened :collision: :clipboard:

After successful setup of the admin user I was asked to enter the passpharse to authenticate but the authentication failed without errors and I was just redirected to the same login page.

I deleted the service and the data volumes and repeated the installation process more than once in case I hadn't saved the passphrase correctly but unsuccessfully.

The outcome was the same with both the "root" and "non-root" Docker images

### What I expected to happen
I expected successful first login.

**Comment by garrettboone** [comment]
When using the eye icon and viewing the passphrase can you confirm it's as expected ( ie without extra spaces)? Anything unusual about the passphrase? How are you entering it: manually, or pasting?

**Comment by eliasbalasis** [comment]
I am pasting but I have checked character by character using the eye icon, the passphrase is correct.

**Comment by garrettboone** [comment]
What if you use a different passphrase? (or have you done that already)

**Comment by eliasbalasis** [comment]
The passphrases I used meet all the requirements, special characters, numbers, letters etc.
but even simple passphrases without special characters didn't work.

**Comment by eliasbalasis** [comment]
I have just tried with earlier version "3.4.0-ce-non-root" and simple passphrase but same outcome unfortunately.

**Comment by eliasbalasis** [comment]
Indeed, it was browser related finally.
I cleared everything I could including the CSRF token and I managed to login.
