### ISSUE TITLE
Cannot create first admin user (Cannot convert value of type `boolean` to integer)

### ISSUE THREAD

**Issue by DachsbauTV** [passbolt/passbolt_docker#179]
Hi,

I am trying ton install passbolt on our Synology NAS via docker compose and everything seemed to have worked fine, however, the command to create the first admin user gives me back the following errors:

**1. When I tried it for the first time this error came up**

`  Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'passbolt.users' doesn't exist
In [/usr/share/php/passbolt/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 160]

ERROR: 1  `

**2. Now after I tried again, it shows this error everytime:**

`  Exception: Cannot convert value of type `boolean` to integer
In [/usr/share/php/passbolt/vendor/cakephp/cakephp/src/Database/Type/IntegerType.php, line 40]

ERROR: 1  `

**This is how my yaml file looked like (again: no errors during the install and all the containers are up and running):**

`  version: '3.9'
services:
  db:
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: https://passbolt.local
      DATASOURCES_DEFAULT_HOST: db
      DATASOURCES_DEFAULT_USERNAME: passbolt
      DATASOURCES_DEFAULT_PASSWORD: P4ssb0lt
      DATASOURCES_DEFAULT_DATABASE: passbolt
      EMAIL_DEFAULT_FROM_NAME: Dachsbau Keys
      EMAIL_DEFAULT_FROM: passbolt@dachsbau.club
      EMAIL_TRANSPORT_DEFAULT_HOST: send.one.com
      EMAIL_TRANSPORT_DEFAULT_PORT:	465
      EMAIL_TRANSPORT_DEFAULT_USERNAME: passbolt@dachsbau.club
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: xxxxxx
      EMAIL_TRANSPORT_DEFAULT_TLS:	100
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 10101:80
      - 10102:443

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
`

**Comment by dlen** [comment]
Hi!

Thanks for your interest in the project! Could you provide some logs and the command you used to create the first user?

**Comment by DachsbauTV** [comment]
Hi @dlen 

Sure, this is what I used:

`docker-compose exec passbolt su -m -c "/usr/share/php/passbolt/bin/cake \
>                                 passbolt register_user \
>                                 -u f****@dachsbau.club \
>                                 -f Fred \
>                                 -l Lordick \
>                                 -r admin" -s /bin/sh www-data
`

**Comment by dlen** [comment]
Hi,

Sorry for the delay. Apparently without any more information looks like migrations were not executed so the database is empty when you try to run the exec command. I tried to reproduce it and it works fine for me. 

Check the connectivity between your containers to ensure passbolt can connect to the database. (Issues with your iptables/nftables setup for example)

For more support on installation issues please refer to the passbolt community forum.
