### ISSUE TITLE
GPG: Not enough random bytes available.  Please do some other work to give the OS a chance to collect more entropy!

### ISSUE THREAD

**Issue by eric-tucker** [passbolt/passbolt_docker#18]
Getting this error when trying to startup the container.

Command:
```
docker run -it --rm -p 80:80 \
  --network $network_name \
  -e db_host=mysql \
  passbolt/passbolt
```

Output:
```
gpg: directory `/var/lib/nginx/.gnupg' created
gpg: new configuration file `/var/lib/nginx/.gnupg/gpg.conf' created
gpg: WARNING: options in `/var/lib/nginx/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/var/lib/nginx/.gnupg/secring.gpg' created
gpg: keyring `/var/lib/nginx/.gnupg/pubring.gpg' created

Not enough random bytes available.  Please do some other work to give
the OS a chance to collect more entropy! (Need 191 more bytes)
```

**Comment by dlen** [comment]
Hi @eric-tucker ! Thanks for your interest on the project We recommend to use rng-tools on host as it was mentioned on https://github.com/passbolt/passbolt_docker/pull/15 

Could you try to install them and let us know if it works better for you?

Thanks!

**Comment by eric-tucker** [comment]
That works.  Perhaps this should be mentioned on the Docker passbolt page since it's a common problem that can't be solved within the container?

https://hub.docker.com/r/passbolt/passbolt/

Thanks for your help!

**Comment by dlen** [comment]
Glad to hear it works :-).
Yeah we are in process of revamp our READMEs to give updated and more accurate information. We were already considering to include this bit of information you are suggesting.
Thanks again!

**Comment by memolipd** [comment]
I still can't get this to work,

rng-tools installed and running on host - still same error.

Looks like the entropy inside the container is being consumed when it goes above 65.

**Comment by memolipd** [comment]
I managed to solve the problem by mounting the host's /dev/urandom folder:

`-v /dev/urandom:/dev/random`
