### ISSUE TITLE
Broken links in email notifications

### ISSUE THREAD

**Issue by schopenhauer** [passbolt/passbolt_docker#181]
Using the latest docker image, I found that some of the email notifications had broken links to the Passbolt logo. The broken image URL is `<APP_FULL_BASE_URL>/img/logo/logo.png`, which returned a 404 error.

The Passbolt app seems to be working perfectly otherwise and running on my custom `<APP_FULL_BASE_URL>` domain.

![Screenshot from 2022-11-16 10-28-34](https://user-images.githubusercontent.com/2085103/202142894-71dee1fd-4efe-4438-b2f7-d54792028af2.png)

**Comment by dlen** [comment]
Thanks for the report!

Does this happen to all your email notifications? Can you access manually the URL of the image?

**Comment by stripthis** [comment]
Additionally to @dlen questions, can your webmail reach that URL also. For example if it's hosted on an internal network and you are using Gmail, it is expected not to work, can we rule thatout?

**Comment by schopenhauer** [comment]
Yes, the <APP_FULL_BASE_URL>/img/logo/logo.png URL is the one I took from the HTML code of the email notification, so it seems to be broken there. We can rule out any image-blocking from my email client, etc. as I tried to access this file via the web browser with the same result, i.e. 404 code.

**Comment by Tecnobutrul** [comment]
Hello @schopenhauer! Is this still happening?

**Comment by schopenhauer** [comment]
This seems to be fixed, not an issue anymore in the latest docker image.
