### ISSUE TITLE
Push docker images for aarch64 (ARM)

### ISSUE THREAD

**Issue by mgoerens** [passbolt/passbolt_docker#184]
(This is not exactly a bug but I cannot seem to use the forum at the moment, this just redirects me to a blank page... Sorry if this is not the right place for this request...)

Following up on #135 it seems to be doable in a few steps to build a docker image for ARM. This is especially useful when deploying passbolt on a Raspberry PI.

It would be a great addition to provide official support, and push such images directly on docker Hub, avoiding users the need to have to rebuild images manually.

Useful link for that purpose: https://docs.docker.com/build/building/multi-platform/

**Comment by dlen** [comment]
Hi, @mgoerens we are actually building aarch64 internally for people using M1 so we will definitely publish arm images in the near future. It's on our radar!

**Comment by kirtan403** [comment]
When can we have this?

**Comment by Tecnobutrul** [comment]
Hi @kirtan403 ! We have an open ticket for this, so arm images will be publicly available very soon.

**Comment by sigma2017** [comment]
Also waiting with great interest docker arm image!

**Comment by ajitesh1828** [comment]
Thank you @Tecnobutrul . Waiting for ARM image to run it on M1. Great work, cheers!!

**Comment by dlen** [comment]
New ARM images have been published to docker hub starting with 3.12.0-3-ce and 3.12.0-3-pro, please let us know if you test them!

https://hub.docker.com/r/passbolt/passbolt/tags

Enjoy!

**Comment by samuellhwarren** [comment]
Testing 3.12.0-3-ce
