### ISSUE TITLE
helm chart for kubernetes?

### ISSUE THREAD

**Issue by migs35323** [passbolt/passbolt_docker#185]
I would want to ask if we could have official passbolt helm charts for deploy in k8s, there are some charts in artifact hub but it would be great if we could get "official ones"

sadly bitnami doesn't provide passbolt charts

**Comment by dlen** [comment]
Yes! We will publish an official one in the upcoming weeks to gather feedback from the community so stay tuned

**Comment by dlen** [comment]
Hi, please check out https://github.com/passbolt/charts-passbolt
