### ISSUE TITLE
Official passbolt docker image use deprecated php version

### ISSUE THREAD

**Issue by pe4k** [passbolt/passbolt_docker#188]
Docker image uses php 7.4, even if this environment is isolated, it should be upgraded to v8 at least.

**Comment by stripthis** [comment]
Hello @pe4k, passbolt images are based on Debian, where PHP 7.4 is still supported (and fixes from v8 are backported) by the Debian security team. We'll propose PHP 8 when it's supported as part of Debian stable version.
