### ISSUE TITLE
Container starts up and reports installation success - nothing happens hitting localhost

### ISSUE THREAD

**Issue by eric-tucker** [passbolt/passbolt_docker#19]
Eventually (after the GPG delay waiting for Entropy), get this:

```
     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
---------------------------------------------------------------
 Datasource : default
 File :/var/www/passbolt/app/tmp/schema/default_default.sql
 Success: the database was saved on file!
---------------------------------------------------------------

 Passbolt installation success! Enjoy! ☮


[etucker: passbolt]$ 
```

Hitting the browser at localhost, nothing happens.  The chrome debug tools show "cancelled" hitting http://localhost

Colleague receives the same behaviour.  Curl on CLI outputs nothing:
```
[etucker: ~]$ curl localhost
[etucker: ~]$ 
```
Despite port 80 actually listening:

```
[etucker: ~]$ nc -z localhost 80
[etucker: ~]$ echo $?
0
```

**Comment by dlen** [comment]
Hi @eric-tucker! Again, thanks for your interest in passbolt :-)

Seems to be some problem with the internal application 301 redirect in the container environment. I will try to dig into this ASAP, will keep you posted.

**Comment by eric-tucker** [comment]
Thanks so much for the quick updates.  Really appreciate it!

**Comment by eric-tucker** [comment]
Any updates?  Anxious to try pass out out!

**Comment by dlen** [comment]
Hi @eric-tucker.
Apologies for the delay. This issue will be solved next week since there is a ton of stuff on the backlog with higher priorities :(
Thanks a lot for your patience!

**Comment by dlen** [comment]
Hi again @eric-tucker 
Since there is no fix for this issue yet a workaround is to use https instead of http.

**Comment by eric-tucker** [comment]
@dlen thanks.  That works.  Though now I have to figure out how to create users.  :)

**Comment by dlen** [comment]
hi @eric-tucker try running this on the container: ```su -m -c "/var/www/passbolt/app/Console/cake passbolt register_user -u your@email.com -f FirstName -l LastName -r admin" -ls /bin/bash nginx```
