### ISSUE TITLE
Issue with installing using docker-compose

### ISSUE THREAD

**Issue by samuellhwarren** [passbolt/passbolt_docker#194]
## IMPORTANT :hand: :point_up: Please read

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

If you still want to report a bug please take a look first on the other open/closed tickets to avoid duplicating issues.

### How to provide a good issue report:
- Provide all the information you can collect about your problem
- Provide log outputs from (some examples follow):
  - /var/www/passbolt/tmp/logs/error.log
  - /var/log/nginx/error.log
  - curl -vvvLk http://passboltdomain
  - Any other sources you might think will help to solve the problem

### What you did :memo:
I took the docker-compose file and installed it using portainer stacks and following instructions from your site. Both times, I get the following error in the docker logs for the Passbolt container: "exec /usr/bin/wait-for.sh: exec format error"
I run this on a Raspberry pi 4, running aarch64, 16gb ram. 

### What happened :collision: :clipboard:
Container refuses to start.
### What you expected to happen
I am not sure how to get more info to get past this.

**Comment by Tecnobutrul** [comment]
Hi @samuellhwarren! This is not an error, this is due to the fact that the passbolt docker image doesn't provide multi architecture support. Currently is working just for linux/amd64 arch.

The development of a multi-arch docker image is in progress so it will be ready very soon.

**Comment by Tecnobutrul** [comment]
Related to #184

**Comment by samuellhwarren** [comment]
perfect! I will follow and look forward to trying it out!
