### ISSUE TITLE
New docker compose install failed: SQLSTATE[HY000] [1045] Access denied for user 'passbolt'@'172.19.0.3' (using password: YES)

### ISSUE THREAD

**Issue by K1WIZ** [passbolt/passbolt_docker#195]
Performed new docker-compose isntall via directions on main site: 
wget "https://download.passbolt.com/ce/docker/docker-compose-ce.yaml"
wget "https://github.com/passbolt/passbolt_docker/releases/latest/download/docker-compose-ce-SHA512SUM.txt"
sha512sum -c docker-compose-ce-SHA512SUM.txt && echo "Checksum OK" || (echo "Bad checksum. Aborting" && rm -f docker-compose-ce.yaml)
docker-compose -f docker-compose-ce.yaml up -d

Docker compose file:
`version: '3.3'
services:
  db:
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: https://passbolt.local
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 80:80
      - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:`

I get the following error shown in the logs for the DB and the passbolt containers:

DB:
`Version: '10.3.38-MariaDB-1:10.3.38+maria~ubu2004'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2023-04-12 14:54:56 9 [Warning] Access denied for user 'passbolt'@'172.19.0.3' (using password: YES)
2023-04-12 14:54:57 10 [Warning] Access denied for user 'passbolt'@'172.19.0.3' (using password: YES)
2023-04-12 14:54:57 11 [Warning] Access denied for user 'passbolt'@'172.19.0.3' (using password: YES)`

Passbolt:
`[12-Apr-2023 14:54:59] NOTICE: systemd monitor interval set to 10000ms
2023-04-12 14:55:00,081 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-12 14:55:00,081 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-12 14:55:00,081 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Exception: Connection to Mysql could not be established: SQLSTATE[HY000] [1045] Access denied for user 'passbolt'@'172.19.0.3' (using password: YES)
In [/usr/share/php/passbolt/vendor/cakephp/cakephp/src/Database/Driver.php, line 133]
Exception: Connection to Mysql could not be established: SQLSTATE[HY000] [1045] Access denied for user 'passbolt'@'172.19.0.3' (using password: YES)
In [/usr/share/php/passbolt/vendor/cakephp/cakephp/src/Database/Driver.php, line 133]`

This was not an attempt to stand up a production instance, but I was just installing it in my home lab docker host to evaluate the software.   I can't seem to get past this.   It seems the passbolt container is unable to authenticate with the DB, though the error says it is using a password.

**Comment by dlen** [comment]
Hi!

I'm unable to reproduce your issue. Could it be some database volume dangling that contains a different auth credentials that are not working anymore?

Cleaning up volumes and try to run the stack again should work. For more support you could use the forum: https://community.passbolt.com

**Comment by K1WIZ** [comment]
This was a new install on a new docker host.  no dangling DB volumes.  Used instructions from official website and saw this error.   I repeated a fresh install on another docker host using same instructions and was able to reproduce this.
