### ISSUE TITLE
Passbolt in docker on rasberry pi 64 bit with cloudflare tunnels 

### ISSUE THREAD

**Issue by Fzibi21** [passbolt/passbolt_docker#196]
I am trying to get Passbolt in docker on a raspberry pi installed. 
I am using the image docker anatomicjc/passbolt:latest-ce-non-root-multiarch and mariadb

it all seems to install but then when i try to run the command for the 1st admin user do i get error message:
/usr/share/php/passbolt/bin/cake: not found 

I would love to be able to install it on a raspberry pi in docker some advice or help would be great

**Comment by dlen** [comment]
Hi!

We now publish arm images you could try and use passbolt/passbolt:3.12.0-3-ce that is shipped for ARM. If you happen to have the same issue please let us know.

**Comment by Fzibi21** [comment]
awesome i will try it out and will report if it still give me the error.
is there a version that can be updated if need be  ?
This looks like a stand alone version and not something that can be updated such as latest

**Comment by Fzibi21** [comment]
will give it a shot and will report if that works

**Comment by Fzibi21** [comment]
still giving the same error 

sh: 1: ./usr/share/php/passbolt/bin/cake: not found

wenn execucitng with changed values
$ docker-compose -f docker-compose-ce.yaml exec passbolt su -m -c "/usr/share/php/passbolt/bin/cake \
                                passbolt register_user \
                                -u <your@email.com> \
                                -f <yourname> \
                                -l <surname> \
                                -r admin" -s /bin/sh www-data

**Comment by dlen** [comment]
It works for me:

```
❯ docker-compose -f docker-compose.yaml exec passbolt su -m -c "/usr/share/php/passbolt/bin/cake passbolt register_user -u yours@email.com -f firstname -l lastname -r admin" -s /bin/sh www-data

     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
-------------------------------------------------------------------------------
User saved successfully.
To start registration follow the link provided in your mailbox or here:
https://passbolt.local/setup/install/9c1630c0-a9ac-47b8-be53-0b2361
```

You are missing the -f and -l flag values, check again your command :)

**Comment by Fzibi21** [comment]
i am getting this error when running it now:
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
-------------------------------------------------------------------------------
Exception: Connection to Mysql could not be established: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
In [/usr/share/php/passbolt/vendor/cakephp/cakephp/src/Database/Driver.php, line 133]
