### ISSUE TITLE
duo mfa authentification 

### ISSUE THREAD

**Issue by happydayxxl** [passbolt/passbolt_docker#198]
## duo authentification 
* Passbolt Version: v3.9.4 - commit 43edcbb

### What you did
Want to connect my account with the passbolt app
download the passbolt app on my apple device. Scanned the QR code, typed in my passphrase after that i got a error message

### What happened
error message poped up "session authorization failed"

### What you expected to happen
request to duo to authenticate with it

with the duo mfa deactivated, everything works and I can get to my passwords

**Comment by garrettboone** [comment]
Related: https://github.com/passbolt/passbolt_help/pull/85

**Comment by happydayxxl** [comment]
thanks
