### ISSUE TITLE
Docker images to be upgraded to PHP 8.2

### ISSUE THREAD

**Issue by schopenhauer** [passbolt/passbolt_docker#200]
It seems like the latest Docker image of Passbolt Pro ([latest-pro](https://hub.docker.com/layers/passbolt/passbolt/latest-pro/images/sha256-64456efb971a5c62ea00c3070f3d0ffeec026817340ff520157efe25a7bb9997?context=explore)) still runs on PHP 7.4. This should be upgraded to PHP 8.2 for all Docker images, as Passbolt is compatible according to the release notes for [v4.0.0](https://help.passbolt.com/releases/pro/get-up-stand-up).

**Comment by dlen** [comment]
Hello @schopenhauer !

Yes, you are right, passbolt supports php 8.2 and we will update it. Our docker images are, for now, based on debian and we will rely on their release cycle to save us some work and version pinning. Debian Bookworm will be the next stable and it should be released around the 10th of June, it will come with php8.x as default and so our images too.

**Comment by dlen** [comment]
We are publishing docker hub tags version 4.0.2-2* (pro and ce) that come with php8 and bookworm. Let us know if you find any issues!
