### ISSUE TITLE
ios app passwort view

### ISSUE THREAD

**Issue by happydayxxl** [passbolt/passbolt_docker#203]
I am using the latest passbolt ce version and want to fetch a password without a encrypted description, but this does not work.

### what i did:
cant get the password via the ios app:
<img src="https://github.com/passbolt/passbolt_docker/assets/85102028/675d7397-5160-4711-ac75-dd1cf3f9599f" width="250">

after enable description encryption on a browser:
<img src="https://github.com/passbolt/passbolt_docker/assets/85102028/162fc5d4-e70f-4d94-8c16-6e06f47e7a6f" width="250">

... i can fetch the password:
<img src="https://github.com/passbolt/passbolt_docker/assets/85102028/9e93f6a6-b0fe-47fb-96ae-7ff9fcd644bc" width="250">

**Comment by dlen** [comment]
Hello @happydayxxl without more information is hard to say if this is even a problem coming from the container or from the API.

Maybe @pabloelcolombiano or @stripthis want to pitch in.

**Comment by happydayxxl** [comment]
> 

how can i provide more information?

**Comment by dlen** [comment]
I just cross-checked with the mobile team and this is a known issue with the ios app. We are waiting for the next app version to be approved by the Apple store. Sorry about the inconvenience. 

I will close this issue if it persists with the next ios app release feel free to reopen!
