### ISSUE TITLE
Unsupported auth type: NTLM - it's possible to changed?

### ISSUE THREAD

**Issue by JoseArellanoV** [passbolt/passbolt_docker#205]
HI all, im deploying passbolt on docker swarm cluster, all good so fare, but we are trying to configure SMTP server and we get an error.

Our server is a rely without autentication on port 25, without TLS

when use ./bin/cake passbolt send_test_email   --recipient=

we gets:

Could not send the test email.
Error: Unsupported auth type: NTLM

how we can change auth type for this kind of server?

Thanks!

**Comment by dlen** [comment]
Hi, @JoseArellanoV your ticket would be better suited on the https://github.com/passbolt/passbolt_api repository. Please open it in that repository so the development team can help you.

**Comment by ishanvyas22** [comment]
Hey @JoseArellanoV, thanks for bringing this issue up. We are working on a fix and provide a release soon (Ticket for internal reference: PB-25472).

**Comment by ishanvyas22** [comment]
Hey @JoseArellanoV, this has been fixed with [v4.1.2](https://github.com/passbolt/passbolt_api/releases/tag/v4.1.2).

**Comment by JoseArellanoV** [comment]
Thanks!!!
