### ISSUE TITLE
blank page when guessing how to use

### ISSUE THREAD

**Issue by eoli3n** [passbolt/passbolt_docker#215]
```
$ docker compose -f docker-compose-ce.yaml up
```
Then, I guess, that I need to access http://localhost

![passbold](https://github.com/passbolt/passbolt_docker/assets/14223657/b78f1b5b-a827-4c39-80eb-f35debb79df4)

**Comment by garrettboone** [comment]
No need to guess, there are instructions: https://help.passbolt.com/hosting/install/ce/docker.html

**Comment by eoli3n** [comment]
Great, then my last guess is that it should be linked at the top of the README, saving time for users.
Thanks !
