### ISSUE TITLE
TOTP gets removed when editing the description via the info box

### ISSUE THREAD

**Issue by EmnichtdaYT** [passbolt/passbolt_docker#219]
# How to reproduce
1. Debian 11 in KVM
2. Follow https://help.passbolt.com/hosting/install/ce/docker.html
3. Change tag to `passbolt/passbolt:4.4.1-1-ce` in compose yaml
4. Finish registration via link in Firefox
5. Create new password via the web interface
6. Add TOTP to the password via the web interface
7. Open info box by clicking on the info icon on the top right
8. Edit the description of the password via the info box

**=> The TOTP is gone!**
# Versions used
- Debian 11 in KVM
- passbolt/passbolt:4.4.1-1-ce
- Firefox 115.5.0 esr **and** 120.0
- Passbolt Firefox extension 4.4.0

**Comment by qntoni** [comment]
Hello @EmnichtdaYT, 
I have been able to reproduce this issue.

We handled this behaviour, we will release the hotfix beggining of the next week. 

Thanks again for your contribution, we really appreciated it. 😉

**Comment by qntoni** [comment]
Hello @EmnichtdaYT,

I wanted to let you know that the bug was fixed and v4.4.2 has been published on the [Chrome Web Store](https://chrome.google.com/webstore/detail/passbolt-open-source-pass/didegimhafipceonhjepacocaffmoppf).

I know you mentioned Firefox, but it still needs to be reviewed on their side, same for Edge. 

Best regards,

**Comment by RandomUser0815** [comment]
Is it possible, that this is still an issue @qntoni ? I created a password, added an OTP token. 

After moving the password to a folder, the token is gone.

As you hopefully understand I don't want to try to reproduce this, and lock me out of another account...

Passbolt 4.7.0
PHP version 8.1.2-1ubuntu2.17
Ubuntu 22.04.4 LTS

**Comment by qntoni** [comment]
Hello @RandomUser0815, I have not being able to reproduce this issues on Ubuntu 22.04 as well as Debian 12. 

Please, could you tell me which client version are you using? You can hover the little heart icon on bottom right.

Best regards
