### ISSUE TITLE
Latest version - can't logged in

### ISSUE THREAD

**Issue by MarekPep** [passbolt/passbolt_docker#22]
I pulled latest version of passbolt yesterday and create new containers (mysql and passbolt). 
(p.s. how to upgrade only passbolt without lost gpgkeys/accounts?)

In new version I can't logged in!

I will describe step by step what I did:

**1. /var/www/passbolt/app/Console/cake passbolt register_user -u mail-f Marek -l Pep -r admin** 

**2. Go to registered link in firefox and see this message:**

![passb_0](https://user-images.githubusercontent.com/29633605/27443744-61436b22-5774-11e7-9f97-bcab691d0467.jpg)

**3. Going to https://addons.mozilla.org/en-US/firefox/addon/passbolt/versions/beta and install:**

 attempt 1 - Version 1.5.1rc2 (and continue register)
 attempt 2 - Version 1.5.1rc1 (delete rc2 and register again)
 attempt 3 - Version 1.6.0 (delete rc1 and register again)

**4. Start register (DOWNLOAD SECRET KEY not work!)**

![passb_1](https://user-images.githubusercontent.com/29633605/27443899-e17cf0ce-5774-11e7-8bfc-48ecf8e7f601.jpg)

**5. In end of register i can't logged in. Only see:**

 "Loading, please wait" 

![passb_loading](https://user-images.githubusercontent.com/29633605/27443762-7500efae-5774-11e7-82ef-1e8030fafc90.jpg)

I try 3 attepmts in different plugin version (and different account).

**6.  Error in log file - /var/www/passbolt/app/tmp/logs/error.log:**

2017-06-22 15:25:22 Warning: Warning (512): _cake_model_ cache was unable to write 'default_passbolt_users' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
Cache::write() - CORE/Cake/Cache/Cache.php, line 328
DataSource::_cacheDescription() - CORE/Cake/Model/Datasource/DataSource.php, line 310
DataSource::describe() - CORE/Cake/Model/Datasource/DataSource.php, line 135
Mysql::describe() - CORE/Cake/Model/Datasource/Database/Mysql.php, line 333
Model::schema() - CORE/Cake/Model/Model.php, line 1397
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1438
DboSource::_parseKey() - CORE/Cake/Model/Datasource/DboSource.php, line 2882
DboSource::conditionKeysToString() - CORE/Cake/Model/Datasource/DboSource.php, line 2833
DboSource::conditions() - CORE/Cake/Model/Datasource/DboSource.php, line 2714
DboSource::buildStatement() - CORE/Cake/Model/Datasource/DboSource.php, line 2007
DboSource::buildAssociationQuery() - CORE/Cake/Model/Datasource/DboSource.php, line 1738
DboSource::read() - CORE/Cake/Model/Datasource/DboSource.php, line 1182
Model::_readDataSource() - CORE/Cake/Model/Model.php, line 3038
Model::find() - CORE/Cake/Model/Model.php, line 3010
DboSource::query() - CORE/Cake/Model/Datasource/DboSource.php, line 604
Model::__call() - CORE/Cake/Model/Model.php, line 834
User::findById() - APP/Controller/AppController.php, line 246
AppController::_disconnectUserIfAccountDisabled() - APP/Controller/AppController.php, line 246
AppController::beforeFilter() - APP/Controller/AppController.php, line 108
AuthController::beforeFilter() - APP/Controller/AuthController.php, line 25
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - CORE/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
require - APP/webroot/index.php, line 111
[main] - ROOT/index.php, line 41

2017-06-22 15:25:22 Warning: Warning (512): SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_users) [<a href='http://php.net/splfileinfo.openfile'>splfileinfo.openfile</a>]: failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
FileEngine::_setKey() - CORE/Cake/Cache/Engine/FileEngine.php, line 356
FileEngine::read() - CORE/Cake/Cache/Engine/FileEngine.php, line 158
Cache::read() - CORE/Cake/Cache/Cache.php, line 363
DataSource::_cacheDescription() - CORE/Cake/Model/Datasource/DataSource.php, line 306
Mysql::describe() - CORE/Cake/Model/Datasource/Database/Mysql.php, line 373
Model::schema() - CORE/Cake/Model/Model.php, line 1397
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1438
DboSource::_parseKey() - CORE/Cake/Model/Datasource/DboSource.php, line 2882
DboSource::conditionKeysToString() - CORE/Cake/Model/Datasource/DboSource.php, line 2833
DboSource::conditions() - CORE/Cake/Model/Datasource/DboSource.php, line 2714
DboSource::buildStatement() - CORE/Cake/Model/Datasource/DboSource.php, line 2007
DboSource::buildAssociationQuery() - CORE/Cake/Model/Datasource/DboSource.php, line 1738
DboSource::read() - CORE/Cake/Model/Datasource/DboSource.php, line 1182
Model::_readDataSource() - CORE/Cake/Model/Model.php, line 3038
Model::find() - CORE/Cake/Model/Model.php, line 3010
DboSource::query() - CORE/Cake/Model/Datasource/DboSource.php, line 604
Model::__call() - CORE/Cake/Model/Model.php, line 834
User::findById() - APP/Controller/AppController.php, line 246
AppController::_disconnectUserIfAccountDisabled() - APP/Controller/AppController.php, line 246
AppController::beforeFilter() - APP/Controller/AppController.php, line 108
AuthController::beforeFilter() - APP/Controller/AuthController.php, line 25
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - CORE/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
require - APP/webroot/index.php, line 111
[main] - ROOT/index.php, line 41

2017-06-22 15:25:22 Warning: Warning (512): _cake_model_ cache was unable to write 'default_passbolt_users' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
Cache::write() - CORE/Cake/Cache/Cache.php, line 328
DataSource::_cacheDescription() - CORE/Cake/Model/Datasource/DataSource.php, line 310
Mysql::describe() - CORE/Cake/Model/Datasource/Database/Mysql.php, line 373
Model::schema() - CORE/Cake/Model/Model.php, line 1397
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1438
DboSource::_parseKey() - CORE/Cake/Model/Datasource/DboSource.php, line 2882
DboSource::conditionKeysToString() - CORE/Cake/Model/Datasource/DboSource.php, line 2833
DboSource::conditions() - CORE/Cake/Model/Datasource/DboSource.php, line 2714
DboSource::buildStatement() - CORE/Cake/Model/Datasource/DboSource.php, line 2007
DboSource::buildAssociationQuery() - CORE/Cake/Model/Datasource/DboSource.php, line 1738
DboSource::read() - CORE/Cake/Model/Datasource/DboSource.php, line 1182
Model::_readDataSource() - CORE/Cake/Model/Model.php, line 3038
Model::find() - CORE/Cake/Model/Model.php, line 3010
DboSource::query() - CORE/Cake/Model/Datasource/DboSource.php, line 604
Model::__call() - CORE/Cake/Model/Model.php, line 834
User::findById() - APP/Controller/AppController.php, line 246
AppController::_disconnectUserIfAccountDisabled() - APP/Controller/AppController.php, line 246
AppController::beforeFilter() - APP/Controller/AppController.php, line 108
AuthController::beforeFilter() - APP/Controller/AuthController.php, line 25
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - CORE/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
require - APP/webroot/index.php, line 111
[main] - ROOT/index.php, line 41

 **extra in attempt 1:**

 2017-06-22 14:39:10 Error: [ForbiddenException] You need to login to access this location
Request URL: /auth/checkSession.json
Stack Trace:
#0 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(349): GpgAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(AuthController))
#2 [internal function]: AuthComponent->startup(Object(AuthController))
#3 /var/www/passbolt/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 /var/www/passbolt/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#6 /var/www/passbolt/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#9 /var/www/passbolt/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 /var/www/passbolt/index.php(41): require('/var/www/passbo...')
#11 {main}

 **7. chmod -R 777 /var/www/passbolt - but did't help :(**

**Comment by dlen** [comment]
Hi @MarekPep 

Thanks for such a detailed issue. When creating the first admin user could you do it as the nginx user, like this: 
```su -m -c "/var/www/passbolt/app/Console/cake passbolt register_user -u mail-f Marek -l Pep -r admin" -ls /bin/bash nginx```

Let's see if this helps you with some of the errors.

**Comment by MarekPep** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Hi
it's work now! (1.5.1.rc1 plugin) thx
when new version of passbolt docker?
Dnia Piątek, 23 Czerwca 2017 12:12 Diego Lendoiro <notifications@github.com> napisał(a)

Hi @MarekPep
Thanks for such a detailed issue. When creating the first admin user could you do it as the nginx user, like this: su -m -c "/var/www/passbolt/app/Console/cake passbolt register_user -u mail-f Marek -l Pep -r admin" -ls /bin/bash nginx
Let's see if this helps you with some of the errors.
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/passbolt/passbolt_docker","title":"passbolt/passbolt_docker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/passbolt/passbolt_docker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dlen in #22: Hi @MarekPep \r\n\r\nThanks for such a detailed issue. When creating the first admin user could you do it as the nginx user, like this: \r\n```su -m -c \"/var/www/passbolt/app/Console/cake passbolt register_user -u mail-f Marek -l Pep -r admin\" -ls /bin/bash nginx```\r\n\r\nLet's see if this helps you with some of the errors."}],"action":{"name":"View 
Issue","url":"https://github.com/passbolt/passbolt_docker/issues/22#issuecomment-310628092"}}}
// ]]>

**Comment by MarekPep** [comment]
Hi

it's work now! (1.5.1.rc1 plugin) thx
when new version of passbolt docker?

**Comment by MarekPep** [comment]
and still DOWNLOAD SECRET KEY not work

**Comment by dlen** [comment]
Glad to hear that!

New docker version is coming out right now. About the secret key download could you reproduce with the new docker hub image version that has just been released?

**Comment by MarekPep** [comment]
yes, of corse
registration/login -> ok
download secret key -> still not work, log messages:

2017-06-23 16:07:15 Warning: Warning (512): SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_users) [<a href='http://php.net/splfileinfo.openfile'>splfileinfo.openfile</a>]: failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
FileEngine::_setKey() - CORE/Cake/Cache/Engine/FileEngine.php, line 356
FileEngine::write() - CORE/Cake/Cache/Engine/FileEngine.php, line 116
Cache::write() - CORE/Cake/Cache/Cache.php, line 317
DataSource::_cacheDescription() - CORE/Cake/Model/Datasource/DataSource.php, line 310
Mysql::describe() - CORE/Cake/Model/Datasource/Database/Mysql.php, line 373
Model::schema() - CORE/Cake/Model/Model.php, line 1397
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1438
DboSource::_parseKey() - CORE/Cake/Model/Datasource/DboSource.php, line 2882
DboSource::conditionKeysToString() - CORE/Cake/Model/Datasource/DboSource.php, line 2833
DboSource::conditions() - CORE/Cake/Model/Datasource/DboSource.php, line 2714
DboSource::buildStatement() - CORE/Cake/Model/Datasource/DboSource.php, line 2007
DboSource::buildAssociationQuery() - CORE/Cake/Model/Datasource/DboSource.php, line 1738
DboSource::read() - CORE/Cake/Model/Datasource/DboSource.php, line 1182
Model::_readDataSource() - CORE/Cake/Model/Model.php, line 3038
Model::find() - CORE/Cake/Model/Model.php, line 3010
DboSource::query() - CORE/Cake/Model/Datasource/DboSource.php, line 604
Model::__call() - CORE/Cake/Model/Model.php, line 834
User::findById() - APP/Controller/AppController.php, line 246
AppController::_disconnectUserIfAccountDisabled() - APP/Controller/AppController.php, line 246
AppController::beforeFilter() - APP/Controller/AppController.php, line 108
AuthController::beforeFilter() - APP/Controller/AuthController.php, line 25
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - CORE/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
require - APP/webroot/index.php, line 111
[main] - ROOT/index.php, line 41

2017-06-23 16:07:15 Warning: Warning (512): _cake_model_ cache was unable to write 'default_passbolt_users' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
Cache::write() - CORE/Cake/Cache/Cache.php, line 328
DataSource::_cacheDescription() - CORE/Cake/Model/Datasource/DataSource.php, line 310
Mysql::describe() - CORE/Cake/Model/Datasource/Database/Mysql.php, line 373
Model::schema() - CORE/Cake/Model/Model.php, line 1397
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1438
DboSource::_parseKey() - CORE/Cake/Model/Datasource/DboSource.php, line 2882
DboSource::conditionKeysToString() - CORE/Cake/Model/Datasource/DboSource.php, line 2833
DboSource::conditions() - CORE/Cake/Model/Datasource/DboSource.php, line 2714
DboSource::buildStatement() - CORE/Cake/Model/Datasource/DboSource.php, line 2007
DboSource::buildAssociationQuery() - CORE/Cake/Model/Datasource/DboSource.php, line 1738
DboSource::read() - CORE/Cake/Model/Datasource/DboSource.php, line 1182
Model::_readDataSource() - CORE/Cake/Model/Model.php, line 3038
Model::find() - CORE/Cake/Model/Model.php, line 3010
DboSource::query() - CORE/Cake/Model/Datasource/DboSource.php, line 604
Model::__call() - CORE/Cake/Model/Model.php, line 834
User::findById() - APP/Controller/AppController.php, line 246
AppController::_disconnectUserIfAccountDisabled() - APP/Controller/AppController.php, line 246
AppController::beforeFilter() - APP/Controller/AppController.php, line 108
AuthController::beforeFilter() - APP/Controller/AuthController.php, line 25
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE/Cake/Event/CakeEventManager.php, line 243
Controller::startupProcess() - CORE/Cake/Controller/Controller.php, line 677
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 189
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
require - APP/webroot/index.php, line 111
[main] - ROOT/index.php, line 41

**Comment by MarekPep** [comment]
the same in: my profile -> menage your keys -> unable to download private/public key

**Comment by dlen** [comment]
Hi again, 

Regarding the errors on the logs please make sure that the owner all the files under /var/www/passbolt is nginx. You could run this: ```chown -R nginx:nginx /var/www/passbolt```
Regarding the errors on the download secret keys: Which version of firefox and the extension are you using?

**Comment by MarekPep** [comment]
I run chown -R nginx:nginx /var/www/passbolt
and still not work: my profile -> menage your keys -> unable to download private/public key
but no errors in log file

Firefox 54.0 (32 bit)
Extensiosn 1.6.0-rc1

**Comment by MarekPep** [comment]
sorry, it's work! but no info on GUI... 

I found this files in firefox download directory:
passbolt_public.asc
passbolt_pprivate.asc

**Comment by dlen** [comment]
Happy to hear that is working 🎉
