### ISSUE TITLE
Publish docker container in version 4.5

### ISSUE THREAD

**Issue by waliwdenko** [passbolt/passbolt_docker#220]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to an installation: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt Browser Extensions.
For passbolt API, docker, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new Browser Extension bug please use the following format:

## ISSUE NAME
* Passbolt Version: 4.4.2
* Platform and Target: Docker
-- Browser: Chrome
-- Web server: Nginx

### What you did
We have Passbolt 4.4.2-1 in Docker. Docker repository dont have version 4.5, but Chrome extension is current 4.5. 

### What happened
Chrome extension in version 4.5 wont work with older (4.4.2) passbolt

### What you expected to happen
Publish docker containers for passbolt 4.5

**Comment by garrettboone** [comment]
How does it not work? What happens?

**Comment by waliwdenko** [comment]
> How does it not work? What happens?

When user is logged site is empty (for moment will show screen with "please wait", and after that is only background), when user is logged out and will try recovery access, when he click button from e-mail it works like above (only background shows)

**Comment by dlen** [comment]
Hello, our publication system is automated but unfortunately our pipelines are delayed. Images will be published later today.

**Comment by waliwdenko** [comment]
Ok, we will wait, we had problems even yestarday, i checked right now, and chrome extension was published yesterday.

**Comment by dlen** [comment]
You can also open an issue on the browser extension repo describing your problem.

**Comment by waliwdenko** [comment]
> You can also open an issue on the browser extension repo describing your problem.

Ok, i did it

**Comment by dlen** [comment]
Hey @waliwdenko, sorry for the delay, images are published now. If you are still experiencing issues please open a ticket either in the api repository or continue the conversation in your browser extension repository ticket.
