### ISSUE TITLE
Spelling Mistake in https://github.com/passbolt/passbolt_docker/tree/master/dev Readme.md

### ISSUE THREAD

**Issue by AbhishekTiwari23** [passbolt/passbolt_docker#221]
### What happened :collision: :clipboard:
Received Error after running the command - no such file exist

### What you expected to happen
`docker-compose -f dev/docker-compose-dev.yml up -d`
to `docker-compose -f dev/docker-compose-dev.yaml up -d`

**Comment by ishanvyas22** [comment]
Hey @AbhishekTiwari23, good catch. Feel free to submit a fix.
