### ISSUE TITLE
Docker compose not working 

### ISSUE THREAD

**Issue by Vijaygawate** [passbolt/passbolt_docker#223]
I am trying to bring up passbolt using docker compose but I am getting below error I am not sure if anything is wrong I am doing 

Below is the docker-compose file I am using

version: "3.9"
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: https://passbolt.local
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      EMAIL_TRANSPORT_DEFAULT_HOST: "localhost"
      EMAIL_TRANSPORT_DEFAULT_USERNAME: "null"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - 80:80
      - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:

![Screenshot from 2024-02-20 22-03-00](https://github.com/passbolt/passbolt_docker/assets/88774056/23bf9779-662d-4c4b-8338-e252ddc67ac3)

**Comment by Gamabunta57** [comment]
Hello @Vijaygawate 

You might have a default Nginx page here. What I see from your docker file is that the URL you should point at is `https://passbolt.local/`.

You could either change the `APP_FULL_BASE_URL` in your docker file or you could set `passbolt.local` pointing to the right IP (probably `127.0.0.1` in your case) in your OS hosts file.

Hope it helps
