### ISSUE TITLE
Can not send email - cron.service does not run in docker

### ISSUE THREAD

**Issue by crb-anhtuan-m** [passbolt/passbolt_docker#228]
### What I did :memo:
I installed by a docker-compose yaml file with these images in Ubuntu 20.04.6 LTS, the initialization is done successfully. I can login to the app and use the app but the email function does not work : 

- passbolt/passbolt:4.8.0-1-ce
- mariadb:10.11
- nginxproxy/acme-companion
- jwilder/nginx-proxy:1.6.0

I use SMTP of OVH (ssl port 465).

### What happened :collision: :clipboard:
On the dashboard UI, tab Email server, I try to Send test email but I got the error : 
`"SMTP timeout."`
I follow this article [(https://www.passbolt.com/docs/hosting/troubleshooting/email/)](https://www.passbolt.com/docs/hosting/troubleshooting/email/) to troubleshot the bug : The bug seems to come from the cron system : 
`docker exec -it passbolt-app-container systemctl status cron.service`
> `System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down`

For informations : the STMP params are tested and it works well.

### What you expected to happen
Email must be sent successfully.

**Comment by dlen** [comment]
Hi, passbolt container does not use systemctl. For installation issues please refer to https://community.passbolt.com
