### ISSUE TITLE
Unknown MySQL server host with version 1.6.0

### ISSUE THREAD

**Issue by rgroothedde** [passbolt/passbolt_docker#23]
Using the latest Docker image I'm getting this error:
`ERROR 2005 (HY000): Unknown MySQL server host '...' (-3)`

If I revert to the previous version (1.5.1) everything is ok. So all db environment variables are set correctly.

**Comment by dlen** [comment]
Hi @rgroothedde 
Thanks for you interest in the project! Could you elaborate a little more? For instance it would be nice to know how do you run the docker container, the environment variables you use and their values. Are you using the docker hub image? Are you building from this repo?

**Comment by rgroothedde** [comment]
@dlen My apologies, I made a mistake so this issue is invalid.
