### ISSUE TITLE
Where are the latest release for Docker images ?

### ISSUE THREAD

**Issue by craph** [passbolt/passbolt_docker#230]
Hello everyone,

I wonder where are the latest release for the Docker image of Passbolt ?

Here the latest release mentioned in GitHub is `4.0.0`. 

Are they build in GitLab because I see gitlab-ci file in the repository ? 

Thank you very much.

Best regards,

**Comment by Tecnobutrul** [comment]
Hello @craph! 4.0.0 is the latest version of the passbolt_docker repository, this is correct. We use this repository to build the passbolt/passbolt docker images that we publish on [dockerhub](https://hub.docker.com/r/passbolt/passbolt/). You can check that repository to pull the images with the latests passbolt api versions.

**Comment by craph** [comment]
Hello @Tecnobutrul ,
Thank you very much for the update but something looks strange for me...
I'm using passbolt docker images for many years now and on the dockerhub side I can see that the latest was pushed 3 month ago.
But here in the repository, the latest release 4.0.0 was in Jun 15, 2023... not the same date at the latest version in dockerhub
My latest docker image I have contains the server version 4.9.1...
I'm using it like this : 
```yaml
passbolt:
    image: passbolt/passbolt:latest
```
is it still the correct way to use it ?
Where are the missing release here on this repository ?

But yesterday was published the version 4.10.0 of the passbolt api and there is no new release of the docker image version. Is it normal ?

Thank you very much for your help.
Best regards,

**Comment by craph** [comment]
@Tecnobutrul , @stripthis ,

Please can you reopen this issue ?

**Comment by Tecnobutrul** [comment]
Hello! The passbolt_docker repository version (4.0.0 at this moment) doesn't have to match the passbolt api version (4.10.0). We use this repository to build both ce and pro images, but we don't bump its version with new image releases, because the code doesn't change. We just bump versions when we introduce new changes on this repository.

The new 4.10.0 docker image will be available in the following days.

I hope this clarify your doubts.

**Comment by craph** [comment]
Thank you very much @Tecnobutrul for the update.
