### ISSUE TITLE
Latest version - error on users and shared

### ISSUE THREAD

**Issue by Cu4rach4** [passbolt/passbolt_docker#231]
Last week i update my container to the latest version (by error - image: passbolt/passbolt:latest-ce), all users has a problem when trying to shareing his password. I try to recover a user and gets an error on the web, so i try to manually on cli:

`/bin/cake passbolt recover_user -u my@email.com`

i gets this error:

`error: [TypeError] App\Model\Table\UsersTable::isUsernameCaseSensitive(): Return value must be of type bool, null returned in /usr/share/php/passbolt/src/Model/Table/UsersTable.php on line 279`

Logs:
No error on logs...

Version:

/bin/cake passbolt version

     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
-------------------------------------------------------------------------------
Passbolt CE 4.1.1
Cakephp 4.5.7
www-data@08bc6f4d590a:/usr/share/php/passbolt$

**Comment by dlen** [comment]
Hi @Cu4rach4, 

Thanks for the report. I think @ishanvyas22 or @pabloelcolombiano might want to pitch in for this one.

**Comment by pabloelcolombiano** [comment]
Hi @Cu4rach4,

The piece of code reported in the error does not exist in v4.1.1. It got introduced in v4.4.0, see the [release notes here](https://github.com/passbolt/passbolt_api/releases/tag/v4.4.0).

It looks like your productive code is at version above v4.4.0, but your configuration files are still at v4.1.1.

I am investigating on how this could have happened.

**Comment by Cu4rach4** [comment]
Hola @pabloelcolombiano 

I found why passbolt do not change version, im using a bind volume to all /etc/passbolt not just for jwt and gpg.

I updated to 4.10 but i get an error when i try to recovery my user:

![image](https://github.com/user-attachments/assets/d419cd01-9511-4a9c-9f99-b2a185cc0583)

Passbolt doent give me any error, i was looking on /var/log/ passbolt and nginx.

**Comment by Cu4rach4** [comment]
Fixed!!!

i was using another domain on the deploy, so i use the same name.

thanks!!
