### ISSUE TITLE
Brave browser can not detect extension persists

### ISSUE THREAD

**Issue by ow3ndesu** [passbolt/passbolt_docker#232]
![image](https://github.com/user-attachments/assets/bd3886fa-d4ac-4b3a-bd95-d6334a998e24)

Please help, this error persists.

**Comment by ow3ndesu** [comment]
tried the generated link on firefox and this does not happen

**Comment by dlen** [comment]
Hi @ow3ndesu, 

This issue fits better on the passbolt/passbolt_api repository you can re-open it in that repo. Thanks!
