### ISSUE TITLE
When port 587 is used for email the tls flag should be set to true in app/Config/email.php

### ISSUE THREAD

**Issue by eric-tucker** [passbolt/passbolt_docker#25]
```
SMTP Error: 530 5.7.0 Must issue a STARTTLS command first. m129sm2162575qkc.2 - gsmtp
```

Similiar issue: https://github.com/passbolt/passbolt_api/issues/51

Thanks in advance!

**Comment by dlen** [comment]
Right, we will add this functionality as an environment variable.
Thanks again @eric-tucker !
