### ISSUE TITLE
The healthcheck does not work on docker container

### ISSUE THREAD

**Issue by MarekPep** [passbolt/passbolt_docker#26]
STEPS:

1) Go to -> https://IP_PASBOLT/healthcheck

2) Display:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred.

3) Log file:

2017-06-27 16:07:10 Error: [InternalErrorException] Internal Server Error
Request URL: /healthcheck
Stack Trace:
#0 /var/www/passbolt/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/passbo...', 491)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/passbo...', 491, Array)
#2 /var/www/passbolt/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/passbo...', 491, Array)
#3 /var/www/passbolt/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

**Comment by dlen** [comment]
Hi @MarekPep,

Thanks for your feedback! Seems like `php5-posix` is missing. Will add it to the packages list
