### ISSUE TITLE
multiple share

### ISSUE THREAD

**Issue by MarekPep** [passbolt/passbolt_docker#27]
When I mark multiple password and try to share it all -> share only one (first) password

**Comment by dlen** [comment]
Hi @MarekPep 
We will investigate this issue but seems like it's more an issue for [passbolt_api](https://github.com/passbolt/passbolt_api) repo.

**Comment by stripthis** [comment]
@MarekPep it is currently not possible to share or edit multiple password at once. There is already an open request to that regards. https://github.com/passbolt/passbolt_api/issues/62
