### ISSUE TITLE
App.fullBaseUrl update doesn't uncomment line or allow changing to https

### ISSUE THREAD

**Issue by eric-tucker** [passbolt/passbolt_docker#29]
As a result the emails sent out from the Docker container continue to have http://localhost

Here is the line from the API code email.php.default:
https://github.com/passbolt/passbolt_api/blob/master/app/Config/core.php.default#L126

To be clear, this is the update line that doesn't quite get the job done:
https://github.com/passbolt/passbolt_docker/blob/master/bin/docker-entrypoint.sh#L53

**Comment by dlen** [comment]
Hi @eric-tucker, 

Yeah we are aware of this issue an it has been fixed on the develop branch along with other issues already. Tomorrow a merge into master is expected and a new docker image will be published. Feel free to check the CHANGELOG.md on develop.

**Comment by eric-tucker** [comment]
Thanks!
