### ISSUE TITLE
Use version as image tag for docker image

### ISSUE THREAD

**Issue by rgroothedde** [passbolt/passbolt_docker#31]
Currently there is only a 'latest'  tag for the docker image. 
It would be nice to have image tags for each version of passbolt docker, in order to prevent an automatic upgrade of the container that might break some functionality.

For example, last version there was a breaking change when the environment variable email_tansport was changed to email_transport.

**Comment by dlen** [comment]
Hi @rgroothedde yes, you are right! Tagging was supposed to be working but we had some troubles with the automated builds and the docker hub. So we will push the images on the different versions manually ASAP.
Thanks for bringing up this issue :)

**Comment by dlen** [comment]
1.6.0 and 1.6.1 passbolt docker images have been pushed to our docker hub repository. Please feel free to test them.
Hopefully next releases of passbolt docker would be pushed automatically following this fashion.
Thanks!
