### ISSUE TITLE
No registration option available in latest docker build of passbolt

### ISSUE THREAD

**Issue by vikaskedia** [passbolt/passbolt_docker#33]
I have tried for 2 hours and I still do not get the registration option.

I created a youtube video to demo the bug:

https://www.youtube.com/watch?v=VYfe3ti7lus

**Comment by dlen** [comment]
Hi @vikaskedia!

Thanks for your interest on passbolt! Yes, we are aware public registration is not working at the moment. You can create an admin user executing the folowing command:
`su -m -c "/var/www/passbolt/app/Console/cake passbolt register_user -u mail -f firstname -l lastname -r admin" -ls /bin/bash nginx`

We will fix the public registration in the next release.

**Comment by vikaskedia** [comment]
tx @dlen
