### ISSUE TITLE
Error when try to access in browser

### ISSUE THREAD

**Issue by victorschinaider** [passbolt/passbolt_docker#34]
I setup the passbolt, but the browser is giving me: ERR_SSL_PROTOCOL_ERROR.
Any ideias?

**Comment by dlen** [comment]
Hi, thanks for your interest in passbolt! Could you elaborate more on this issue? Which environment variables are you using to launch the container? How are you accessing the container? Which operating system?

**Comment by victorschinaider** [comment]
Hi, @dlen .
Thanks, i will give more details.

Well, i've a virtualization server wtih an ubuntu virtual machine. In Ubuntu, i have a instance of Docker running. So, i have pulled the mysql, and started the config like the readme says.

```bash
sudo docker run --name mysql -e MYSQL_ROOT_PASSWORD=<password> -e MYSQL_DATABASE=passbolt -e MYSQL_USER=passbolt -e MYSQL_PASSWORD=<password> -v /home/admin01/docker-data/mysql/data:/var/lib/mysql  -d mysql
```

And, then the network started at `172.17.0.3`, so i run the passbolt image:

```bash 
sudo docker run -e db_host=172.17.0.3  -e db_pass=<password>  -d passbolt
```
But it gives no response. In local machine, it gives me "HTTP CODE 400 (BAD REQUEST)"

**Comment by dlen** [comment]
Hi again! Thanks for the information. How are you accessing the container? Are you forwarding ports from the container to the vm? Which ones? Which URL are you using to access passbolt container?

**Comment by victorschinaider** [comment]
Hi, i'm trying to setup in my local machine. So i followed the steps in README.
It's giving 

"Example Domain This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission.
More information..."

**Comment by dlen** [comment]
hi again, you can refer to #36
