### ISSUE TITLE
Inconsistent versioning of docker image

### ISSUE THREAD

**Issue by rgroothedde** [passbolt/passbolt_docker#38]
The docker image with version 1.6.1 was created 21 days ago, passbolt version 1.6.1 was released only 2 days ago. So these versions do not match.

**Comment by stripthis** [comment]
Hi @rgroothedde, Yes, we noticed the issue too. We will match the passbolt docker and api version in the future.

**Comment by rgroothedde** [comment]
@stripthis Can you also please make the newest passbolt version (1.6.1) available as docker image? Thank you!

**Comment by dlen** [comment]
Hi @rgroothedde a new release of the docker image will be pushed to the docker hub this week. Starting with next passbolt_api release passbolt_docker images will have a better syncing.
Sorry for the inconvenience
