### ISSUE TITLE
After installation default page doesn't load

### ISSUE THREAD

**Issue by marianafalzone** [passbolt/passbolt_docker#40]
Hi, 

I followed the instructions from the ticket "After installation default page is Example Domain #36"  where we need to do a:
docker run -e db_host=your_mysql_container_host -e url=passbolt.dev passbolt/passbolt:latest

After doing this, the page sends me an error:

This site can’t be reached

This site on the company, organization or school intranet has the same URL as an external website. 

Try contacting your system administrator.
ERR_ICANN_NAME_COLLISION

I am not sure what do I need to do

**Comment by dlen** [comment]
hi @marianafalzone, thanks for your interest in passbolt! Are you running docker from a windows host? If so, could you please use the domain: `passbolt.local` 
If you are not using windows to run docker could you describe a little bit more which OS are you using and the exact commands used to launch passbolt docker image, as well as mysql container?

**Comment by dlen** [comment]
Hi again! Is there any progress on this issue?

**Comment by marianafalzone** [comment]
Hi Diego,

Sorry for the late response.

I am using a Mac OS X.
I created the image using this command

`docker run -e db_host=<DB_ENDPOINT_FROM_AWS> passbolt:latest`

I am using a RDS from AWS.

I know the connection to the DB works since I ran a different application and I didn't have any issues.

Thanks,

Mariana

**Comment by dlen** [comment]
Hi @marianafalzone, 
Have you exported passbolt.dev hostname or whatever hostname you are using to start passbolt in your /etc/hosts ?

**Comment by marianafalzone** [comment]
Hi,

Yes, I did.

**Comment by dlen** [comment]
If you are running passbolt app on macOS you should expose (port forward) 443 port so you can access it through localhost.
Basically you should run passbolt container the following way:
`docker run -p 443:443 -e db_host=your_mysql_container_host -e url=passbolt.dev passbolt/passbolt:latest`

Then add to /etc/hosts the following line:
`127.0.0.1 passbolt.dev`

And access https://passbolt.dev

There is more information on the [README](https://github.com/passbolt/passbolt_docker#note-on-starting-passbolt-container-on-macos-systems)

**Comment by marianafalzone** [comment]
Thanks Diego!

That worked!

One more question, is there a way to specify the db in the Dockerfile instead of running `docker run -p 443:443 -e db_host=your_mysql_container_host -e url=passbolt.dev passbolt/passbolt:latest` ?

Thanks.

**Comment by dlen** [comment]
hi @marianafalzone, glad to hear that it works! 
To use a static DB_HOST (remember in the latest version of passbolt env variables are uppercased, check the README and CHANGELOG) you could add this line at the beginning of the dockerfile:
`ENV DB_HOST your_host`
However this is not recommended. If you want to stick to static env variables let's say like a scriptable way to run passbolt or, actually, any container you should try [docker-compose](https://docs.docker.com/compose/overview/). There is even a docker-compose [repo for passbolt](https://github.com/dlen/passbolt-compose) you might want to check.

**Comment by dlen** [comment]
I'm closing this issue since the initial problem is now solved
