### ISSUE TITLE
Is there a DB_PORT Variable to specify the db port being used?

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_docker#43]
Hi there

I have multiple db's on the same server so I need to specify a none standard port for mariadb.

How is it best to do that as I cannot start the container due to the connection to the db failing.

Thanks

Edit: Here is the error, but the IP is not correct and does not correspond to the address set with DB_HOST parameter.

ERROR 1045 (28000): Access denied for user 'pb'@'172.17.0.1' (using password: YES)

docker run -d --name="passbolt" --net="bridge" -e TZ="Europe/" -e HOST_OS="Linux" -e "MYSQL_ROOT_PASSWORD"="redacted" -e "MYSQL_DATABASE"="redacted" -e "MYSQL_USER"="redacted" -e "MYSQL_PASSWORD"="redacted" -e "DB_HOST"="Local IP Address" -e "DB_PORT"="3308" -e "URL"="passbolt.local" -p 447:443/tcp passbolt/passbolt

**Comment by dlen** [comment]
Hi @mannp ! Thanks for your interest in the project! Unfortunately passbolt docker image does not yet support specifying a database port through an environment variable. However, it is possible for you to mount the configuration files that fit your needs as a volume in your passbolt container.
We will keep in mind your scenario to roll out a fix in the upcoming release of the image.

**Comment by mannp** [comment]
Hi @dlen ok thats a shame but thanks for considering as a future option.

What internal directory should I mount externally to be able to access these configuration files you refer too please?

Will it be possible to exec the docker without a correct db connection?

**Comment by dlen** [comment]
Regarding the execution without the correct db connection it is not possible, passbolt has to communicate with a database backend.
The list of files you can mount is described on the [README](https://github.com/passbolt/passbolt_docker#configuration-files-subject-to-be-persisted) you are interested in the `database.php` and you can take a look on the default file [here](https://github.com/passbolt/passbolt_api/blob/master/app/Config/database.php.default)
Take a look at the [advanced setup](https://github.com/passbolt/passbolt_docker#advanced-configuration-1) of the README for a glimpse on how to mount the configuration files.

**Comment by mannp** [comment]
Ok thanks but none of those files you have linked talk about specifying db ports in a config file, so I will have to google further.

**Comment by dlen** [comment]
yeah the database.php is the standard cake.php configuration file. Port is an optional parameter of the database hash. More information here: https://book.cakephp.org/2.0/en/development/configuration.html

**Comment by mannp** [comment]
Ok thanks, not familiar with CakePHP only other apps using php7, so presumed they were similar.

Tried to mount /var/www/passbolt/app/Config/ to my local config directory to give me access to all the configs and allow easy backups, but get another error;

/var/www/passbolt/app/Config/gpg/serverkey.private.asc: No such file or directory

Does the docker run as user root or can I set PUID and PGID to set the owner of the config directory?

**Comment by mannp** [comment]
Has DB_HOST to a database on a different machine been test, as I have used the auto create docker on the mac to create a running mariadb on port 3306 and I have pointed my linux docker DB_HOST to that mac docker and it still insists on trying to connect to 172.17.0.1.

ERROR 1045 (28000): Access denied for user 'passbolt'@'172.17.0.1' (using password: YES)

**Comment by mannp** [comment]
Tried again using a remote mariadb with port 3308 in my database.php and I get;

ERROR 2003 (HY000): Can't connect to MySQL server on '192.168.1.60' (111 "Connection refused")

So it appears even with the correct settings in the database.php, the connect still tried on 3306.

**Comment by dlen** [comment]
Hi,
The error you are referring to is related to the `install()` function on the container entrypoint. Database port is not hardcoded but no specified hence mysql client assumes by default 3306 when checking for a previous installation of passbolt.
Introducing the `DB_PORT` env variable should fix this problem.

**Comment by mannp** [comment]
It is specified in the database.php config file which is used, so it should be looking for the correct port from that file? shouldn't it.

Are you saying it needs to be specified in 2 places, for the install and the database.php port?

**Comment by dlen** [comment]
Fixed in the 1.6.2 feel free to re-open if needed

**Comment by mannp** [comment]
Hi @dlen thanks for the update.

I'd moved around my db's to free up 3306 so had it running nicely, but I get this if there is no DB_PORT set and the docker fails to start.

> Unknown suffix '-' used for variable 'port' (value '-p')
mysql: Error while setting value '-p' to 'port'

Once DB_PORT=3306 is added I am all fine again.

Perhaps the docker should default to port 3306 if the DB_PORT env variable is not set or missing?

**Comment by dlen** [comment]
oops! it's due to a last minute change when parsing the config file. Publishing a hotfix now.

Thanks!

**Comment by dlen** [comment]
Hope it's fixed now 😅

**Comment by mannp** [comment]
Hi @dlen just updated and unfortunately there is no change for me.

Getting the same error when I don't have DB_PORT defined.

If I define it as 3306 it works and picks up my existing config with @Enjoy!

**Comment by dlen** [comment]
Hi again @mannp I have just re-checked it and it is working for me without defining the env DB_PORT. Could you try again from master or use the image from docker hub ```docker pull passbolt/passbolt```
