### ISSUE TITLE
Automated Docker setup not fully working on a mac

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_docker#46]
docker run -e DB_HOST=172.17.0.2 passbolt:local
Unable to find image 'passbolt:local' locally
docker: Error response from daemon: repository passbolt not found: does not exist or no pull access.
See 'docker run --help'.

**Automated setup**

In the following example passbolt is launched with the defaults enabled usind mysql official docker container to store passbolt data:

$ docker run -e MYSQL_ROOT_PASSWORD=c0mplexp4ss \
             -e MYSQL_DATABASE=passbolt \
             -e MYSQL_USER=passbolt \
             -e MYSQL_PASSWORD=P4ssb0lt \
             mysql
Once mysql container is running we should extract its ip address. Let's assume 172.17.0.2 for this example

**$ docker run -e DB_HOST=172.17.0.2 passbolt:local**

Point your browser to the passbolt container ip or localhost:exposed_port

**Comment by dlen** [comment]
Hi again @mannp maybe it is a dumb question but have you build the image from this repo as is stated on the README https://github.com/passbolt/passbolt_docker#build-the-image ?
After cloning the repo and building the image you must be able to run the generated image with the tag local or whatever tag you used to build the image.
For instance 
```
:~$ git clone https://github.com/passbolt/passbolt_docker
:~$ cd passbolt_docker 
passbolt_docker:~$ docker build . -t passbolt:local
##docker build output messages...
...
Successfully built e8f0fce0fb3c
Successfully tagged passbolt:local
passbolt_docker:~$  docker run -e MYSQL_ROOT_PASSWORD=<your_root_password> \
             -e MYSQL_DATABASE=passbolt \
             -e MYSQL_USER=passbolt \
             -e MYSQL_PASSWORD=P4ssb0lt \
             mysql
```

Then on a different tab of your favourite terminal:

```
passbolt_docker:~$ docker run -p 443:443 -e DB_HOST=<ip_of_mysql_container> -e URL=passbolt.dev passbolt:local
passbolt_docker:~$ sudo echo "127.0.0.1 passbolt.dev" >> /etc/hosts
```
NOTE: IP address of mysql container can be retrieved using an exec of `ip addr` on the mysql running container or using docker inspect. It is usually '172.17.0.2' if you don't have any other container running but please check in your setup. 
Then point your browser to https://passbolt.dev
If you find the process not automated enough I recommend you to use some docker-compose for passbolt like [this one](https://github.com/dlen/passbolt-compose)
Hope this helps

**Comment by mannp** [comment]
@dlen no I went straight to the Automated Setup and assumed there were no manual steps needed prior to using the automated setup.

I see now there was an offline image to build first, which wasn't obvious to me at the time.

I have moved back to my linux unraid setup as the mac docker was causing me too many issues.

It actually crashed and I lost everything, so I went back to linux unraid and configured it as I had configured the mac docker, but without the external mount point to configs and I am all up and running again, thanks.

Apologies for all the noob questions/issues :)

**Comment by dlen** [comment]
It means automated in the sense that the docker container will automatically create a gpg key, openssl self signed certificate and configuration files. It's automated if you use the `passbolt/passbolt` image from the docker hub, otherwise you have to build the image as described. We will clarify this on the README
