### ISSUE TITLE
301 Redirect loop with SSL offloading

### ISSUE THREAD

**Issue by Kamaradeivanov** [passbolt/passbolt_docker#47]
Hello I try to use the let's encrypt SSL certificate attached to my load-balancer haproxy with Rancher (so my https 443 port is connected to the 80 of the dock passbolt).

Unfortunately when I do that I got a 301 redirect loop and Firefox say : 
The page isn’t redirecting properly

I use the dock passbolt/passbolt:1.6.1-1-alpine

**Comment by dlen** [comment]
Hi @Kamaradeivanov thanks for your interest in passbolt! Please refer to the `SSL` env variable from the section https://github.com/passbolt/passbolt_docker#app-file-variables of the README.

Turn it to false to avoid passbolt to redirect requests to https.

**Comment by Kamaradeivanov** [comment]
Thanks I totally miss this option during my first read...
