### ISSUE TITLE
Email tls config

### ISSUE THREAD

**Issue by pierlon** [passbolt/passbolt_docker#51]
The email TLS config option is incorrectly formatted when transformed with sed. It should not have quotes surrounding the boolean. (See https://github.com/passbolt/passbolt_docker/blob/master/bin/docker-entrypoint.sh#L128)

I'd be happy to make a pull request to fix this.

**Comment by dlen** [comment]
hi @pierlon thanks for the interest in passbolt. You are right, we are aware of this formatting problem, your pull request will be more than welcome :)
