### ISSUE TITLE
Docker Installation did not work 

### ISSUE THREAD

**Issue by shishirtiwari** [passbolt/passbolt_docker#52]
Hi

I created a container with passbolt docker file as given, but i did not install properly and not able to open passbolt on browser.

1. created an ubuntu VM 16.04 

2. installed mysql from docker file
(I think it worked)

3.  installed docker file for passbolt the process started

4. when tried to open passbolt on browser got this message 
Secure connection failed.

5 tried to run it through curl and got this message 
gnutls_handshake() failed

I think the problem is with SSL encryption are there any other steps to be performed as against what is mentioned on read.me file?

![capture](https://user-images.githubusercontent.com/4740406/29241565-10222262-7f9a-11e7-90d1-4ca7fafbc04a.JPG)

**Comment by dlen** [comment]
Hi @shishirtiwari, thanks for your interest in passbolt. Regarding your passbolt container it is running some 'python app.py' which is not part of passbolt stack. Could you elaborate a little more on your setup?
