### ISSUE TITLE
Default url is not changed

### ISSUE THREAD

**Issue by pierlon** [passbolt/passbolt_docker#54]
The 'App.fullBaseUrl' in the 'core.php.default' in passbolt_api is still http://example.com, so the default url isn't being replaced.

One option is to update https://github.com/passbolt/passbolt_docker/blob/master/bin/docker-entrypoint.sh#L54 to `sed -i s:example.com:${URL:-$default_url}:g`, which replaces example.com with the default url, or to change the 'App.fullBaseUrl' to 'passbolt.local' at https://github.com/passbolt/passbolt_api/blob/master/app/Config/core.php.default#L126

**Comment by dlen** [comment]
Hi @pierlon yeah it's a regression bug, we are aware of it and it will be fixed along with some other changes on the next release. See #50
