### ISSUE TITLE
How do we update the docker version to the latest on github please? 1.6.1 to 1.6.2

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_docker#55]
git doesn't appear to be installed on the docker for us to update, so should it update automatically, or we wait for a new build from yourselves?

Thanks.

**Comment by stripthis** [comment]
Hi @mannp, @dlen will release a new version of the docker later this week.

**Comment by stripthis** [comment]
Hi @mannp, @dlen will release a new version of the docker later this week.
