### ISSUE TITLE
Request admin updatable docker via git or other means

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_docker#56]
Hi @dlen my other dockers have ways for me to update them via git, replacing the www file structures or auto updater.

Having the ability to update the passbolt part of the image with the rest of the docker updating with improvements to the base (ubuntu/alpine) build automatically (this part may already happen).

Thanks for your consideration.

**Comment by dlen** [comment]
Hi @mannp thanks for your suggestion! We will keep it in mind for upcoming releases. Anyway you could mount the ```/var/www/passbolt``` directory and update it using git from your host.

**Comment by mannp** [comment]
Hi @dlen ok thanks for keeping it in mind. 

If I mount /var/www/passbolt would it be overwritten by any update your create of the docker image?
