### ISSUE TITLE
Updated to latest docker (1.6.2?) and hovering over the heart shows 1.6.1?

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_docker#57]
Hi @dlen I wondered if I am actually on 1.6.2 and the heart is reporting wrongly of I am on 1.6.1 still?

Thanks for any insight.

**Comment by dlen** [comment]
Hi @mannp heart should report 1.6.2. Are you building the image from the Dockerfile or pulling from the docker hub?

**Comment by mannp** [comment]
Hi @dlen pulling from docker hub passbolt/passbolt

**Comment by mannp** [comment]
@dlen I have removed the docker image and deleted it, then recreated it with my existing config mount.

It still shows v1.6.1 with the heart.

Do I need to do any command line upgrading or should that get done by the docker when its upgraded?

**Comment by mannp** [comment]
@dlen not sure what is going on here but I am not getting your updates...as of this morning 17/08/17

passbolt/passbolt:latest

> bash-4.3# ./app/Console/cake Migrations.migration status
Cake Migration Shell
---------------------------------------------------------------
Application

Current version:
  #1498311597 1498311597_Migration_1.6.1
Latest version:
  #1498311597 1498311597_Migration_1.6.1
---------------------------------------------------------------
Migrations Plugin

Current version:
  #003 003_increase_class_name_length
Latest version:
  #003 003_increase_class_name_length
---------------------------------------------------------------

**Comment by stripthis** [comment]
@mannp it's normal that migration are not showing 1.6.2 or 1.6.3 as these releases do not have database migration script associated with them (eg. you database schema is up to date). The version number of your instance is in app/Config/version.php

**Comment by mannp** [comment]
Hi @stripthis, so that shows I am not on the latest version, which is odd when I have removed and reinstalled the image from scratch;

> <?php
$config = [
        'App.version' => [
                'number' => '1.6.1',
                'name' => 'Fresh'
        ],
];

**Comment by mannp** [comment]
@stripthis @dlen I believe this is a file permissions problem as I not the directories and files you have in your latest build are slightly different (more w) than mine are in my mount config directory.

I have looked at the docker script and it doesn't appear to set any file permissions, which I guess is why if they get out of step they are not able to be updated.
