### ISSUE TITLE
Unable to access default installation with http

### ISSUE THREAD

**Issue by bestlibre** [passbolt/passbolt_docker#59]
When I try to access passbolt without ssl (http only) I get a `400 Bad Request; Request Header Or Cookie Too Large` error. 

I have launch the official mysql container with : `docker run -e MYSQL_ROOT_PASSWORD=passbolt -e MYSQL_DATABASE=passbolt -e MYSQL_USER=passbolt -e MYSQL_PASSWORD=P4ssb0lt --name mysql mysql`.
I have then launched passbolt with : `docker run -p 80:80 -p 443:443 -e SSL=False -e DB_HOST="172.18.0.3" -v /tmp/passbolt/gpg/serverkey.private.asc:/var/www/passbolt/app/Config/gpg/serverkey.private.asc -v /tmp/passbolt/gpg/serverkey.asc:/var/www/passbolt/app/Config/gpg/serverkey.asc passbolt/passbolt`

https seems to work since I got the login page.

If i remove the line `large_client_header_buffers 2 1k;` from the conf/passbolt.conf file, I can load the login page with http.

**Comment by dlen** [comment]
Hi @bestlibre thanks for your interest in passbolt and sorry about the delay on the reply! Also, thanks for your suggestion it will be considered for either increase the limit or removing it!

**Comment by nofear87** [comment]
Same Problem here...just making port 80 public seems to be not enough in docker.
