### ISSUE TITLE
faild to launch

### ISSUE THREAD

**Issue by mitrasero** [passbolt/passbolt_docker#6]
tried to launch container but didnt work ... any idea ?

root@ip-10-210-93-91:~/passbolt# ./launch-container.sh
./launch-container.sh: 4: ./launch-container.sh: source: not found
docker: Error response from daemon: invalid volume spec ":/var/www/passbolt": invalid volume specification: ':/var/www/passbolt'.
See 'docker run --help'.

**Comment by stripthis** [comment]
@dlen  will publish a new version of the docker image this week. Stay tuned.

**Comment by dlen** [comment]
Hi @mitrasero thanks for your feedback!

As @stripthis said a new version has been released and it will be pushed soon to the docker hub. Hope this release solves your problems. Please, create a new ticket if you find any other issues with the new image.
