### ISSUE TITLE
Error when initializing database

### ISSUE THREAD

**Issue by elboletaire** [passbolt/passbolt_docker#61]
There's an error when passbolt initializes that I've been able to avoid just one time, but I'm not able to avoid it again, thus, I've no idea what's causing this.

I'm starting the db container before the passbolt one, to ensure the container initializes (and creates the empty database) before running the passbolt container. Doing this at least I avoid the `unknown host` error that [I've described here](https://github.com/dlen/passbolt-compose/issues/1).

The problem now resides in the `passbolt` initialization. After the private key is written, it tries to do something with the database which fails:

~~~
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/passbolt_passbolt_1/db' at line 1
~~~

Note: the `passbolt_passbolt_1` refers to the passbolt container name (default naming for `docker-compose` containers). I guess that the issue comes from here: https://github.com/passbolt/passbolt_docker/blob/master/bin/docker-entrypoint.sh#L145 but sincerely, I've no idea.

**Comment by dlen** [comment]
Hi @elboletaire this is related to #60

**Comment by elboletaire** [comment]
Unless I'm missing something, this issue is not related to #60 and should be reopened too.

As said in #60 I'm already using version 2 of docker-compose and (after fixing the issue described in #60) I'm only able to get the described error below after initializing the passbolt container.
