### ISSUE TITLE
How to create the first admin account

### ISSUE THREAD

**Issue by x-jokay** [passbolt/passbolt_docker#62]
Everything is up and running using your docker container and mariadb container but how to create the first admin account?

**Comment by mannp** [comment]
> https://www.passbolt.com/help/tech/install#toc_troubleshoot

This section;

> Create the first admin account
> 
> An admin user will be able to manage the other users on passbolt. You will need at least one:
> 
> app/Console/cake passbolt register_user -u me@domain.com -f myFirtsname -l myLastname -r admin
> After the admin user creation, the command line tool will give you a setup link which will also be sent to you by email (if your emails are properly configured). Follow the link given to setup your account.

Docker exec into the docker and execute the above command with your name changed etc.

**Comment by robsiera** [comment]
https://help.passbolt.com/hosting/install/ce/docker talks about _docker-compose exec_ command, but indeed same command works with _docker exec_

**Comment by garrettboone** [comment]
Yes, `docker-compose exec` is equivalent to the `docker exec` command targeting a Compose service. https://docs.docker.com/engine/reference/commandline/compose_exec/
