### ISSUE TITLE
Check for email cron before setting it

### ISSUE THREAD

**Issue by elboletaire** [passbolt/passbolt_docker#63]
The entrypoint should check for a probably existing email cron before setting it up.

It could be probably done with a grep:

~~~bash
if ! grep run-parts /etc/crontabs/root > /dev/null; then
~~~

**Comment by dlen** [comment]
Thanks for your report! It will be fixed as soon as possible :)

**Comment by elboletaire** [comment]
Nice! 😄

**Comment by dlen** [comment]
Gracias por el bug report @elboletaire !

**Comment by elboletaire** [comment]
Lolailo, de nada @dlen. Justo acabamos de empezar a usar passbolt en la empresa porque hasta ahora no habíamos encontrado nada similar (decente). Así que lo más seguro que alguna cosilla más iremos diciendo 😋 

pd. por tu apellido no me hubiera atrevido a pensar que hablaras / fueras español xdd

**Comment by elboletaire** [comment]
Por curiosidad, ¿cómo has deducido que yo sí era español? ¿Sólo con mi nombre? ¿O has visto algún repo mío que te lo ha dejado claro? 🤔

**Comment by dlen** [comment]
Tu nombre ha sido suficiente ;)
