### ISSUE TITLE
More prompt docker updates please :)

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_docker#64]
Hi @dlen, its been 8 days since 1.6.4 was released and the docker is still on 1.6.3

My docker is now exposed to the internet for better testing and updates could be vital to its security :)

Thanks.

Or expose the parts so we can upgrade ourselves :)

**Comment by stripthis** [comment]
Hi @mannp, v1.6.4 do not bring any improvements or security fix it just add a checkbox on the registration page when the site is in demo mode. Don't worry, if we publish security fixes, the docker image will be updated at the same time.

**Comment by mannp** [comment]
Hi @stripthis its also giving me the following in the healthcheck;

Application configuration

 [FAIL] This installation is not up to date. Currently using 1.6.3 and it should be v1.6.4.

I'd prefer all green, if its such a small change, it must be a trivial task to up the docker version?
