### ISSUE TITLE
How to define a SMTP sever which does not need any authentication?

### ISSUE THREAD

**Issue by l00mi** [passbolt/passbolt_docker#70]
e.g. only accessible in the internal network ?

Do we need also to expose a EMAIL_AUTH?

**Comment by l00mi** [comment]
Only removing the `username` / `password` field from actually worked for me that cake mailer does not anymore use any AUTH. Setting them "false" did not work for us.

```
public $default = array(
                'transport' => 'Smtp',
                'from' => array('passbolt@localhost' => 'Passbolt'),
                'host' => 'localhost',
                'port' => 25,
                'timeout' => 30,
                'tls' => false,
);
```

Best might be to remove the lines if EMAIL_USERNAME is set empty?

**Comment by justb81** [comment]
if you set `username / password` to `null` it works the same. the current version of the [`docker_entrypoint.sh`](https://github.com/passbolt/passbolt_docker/blob/master/bin/docker-entrypoint.sh#L127) has sets single quotes around the value given in the environment.

`sed -i "0,/"$default_username"/s:"$default_username":'${EMAIL_USERNAME:-email_user}':" $email_config`

the solution would be to set this to `null` if username is empty.

**Comment by Richigeht** [comment]
Hello,
So I try to do the same but it is just not sending any mails - using a local SMTP (postfix) Server... sending mails via console works great. 
Any idea why this is?
