### ISSUE TITLE
Class "smtpTransport" not found.

### ISSUE THREAD

**Issue by mgluesenkamp** [passbolt/passbolt_docker#72]
Hi,

I don't know, if this is a special docker problem, but only tried the docker version of passbolt. 
I can't send emails after starting the image. I try to recover my own account in a test instance but the docker console gives me this error:

`Class "smtpTransport" not found.`

My email configuration is:

```
EMAIL_TRANSPORT=smtp
EMAIL_HOST=smtp.server.tld
EMAIL_PORT=25
EMAIL_TLS=false
EMAIL_USERNAME=username
EMAIL_PASSWORD=password
```

I also tried two different SMTP servers.

Thanks for help! :)

**Comment by dlen** [comment]
Hi @mypassbot! Thanks for your interest on the project and sorry about the delay 
Could you describe if you are building from the source code or using the docker hub image?

**Comment by bjozet** [comment]
`EMAIL_TRANSPORT=Smtp` should work. Notice the capital 'S'. The variable translates directly into classname, it seem.

**Comment by dlen** [comment]
Closed due to inactivity feel free to reopen if necessary.
