### ISSUE TITLE
Split config and app-essential files

### ISSUE THREAD

**Issue by donbeave** [passbolt/passbolt_docker#74]
Hello, guys!

Thank you for so good product. But I have one question, is it possible in future to split config files, like these:

1) core_config='/var/www/passbolt/app/Config/core.php'
2) db_config='/var/www/passbolt/app/Config/database.php'
3) app_config='/var/www/passbolt/app/Config/app.php'
4) email_config='/var/www/passbolt/app/Config/email.php'
5) gpg_private_key=/var/www/passbolt/app/Config/gpg/serverkey.private.asc
6) gpg_public_key=/var/www/passbolt/app/Config/gpg/serverkey.asc
7) ssl_key='/etc/ssl/certs/certificate.key'
8) ssl_cert='/etc/ssl/certs/certificate.crt'

into separate volume path, in this case it can be more convenient to use this docker with systems like Kubernetes. Because I just need to generate this config only once after install, but container can be restarted after crash or something else and in this case not need to re-generate this data again.

Best regards,
  Alexey Zhokhov.

**Comment by dlen** [comment]
Hi @donbeave sorry about the delay don't know if you are still experiencing this issue with k8s. Have you tried to use confimaps/secrets to render the needed configuration files? You can project on the pod filesystem all this required files and the docker image won't rebuild them if the files are present.
