### ISSUE TITLE
"/docker-entrypoint.sh\": permission denied"

### ISSUE THREAD

**Issue by ASerzhant** [passbolt/passbolt_docker#8]
Hi! 

When I am trying to run Docker with passbolt i am getting next: 

```
~/passbolt_docker-master$ docker run   -e db_host=172.17.0.2 passbolt:1.4.0-alpine
container_linux.go:247: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied".
```

**Comment by dlen** [comment]
Hi @ASerzhant !

Thanks for your interest in passbolt!! Seems like you are building the image from scratch, is that right?
If that is the case seems like when copying the entrypoint script at build time, is not preserving permissions. Could you `chmod +x bin/docker-entrypoint.sh` and run the build process again?

**Comment by ASerzhant** [comment]
Thank you for very fast reaction! 
Yes, I built image according instruction. 
I have changed permissions for the file:  
`-rwxrwxrwx 1 vaultier vaultier 4117 May  5 02:31 docker-entrypoint.sh*`
 but the same error... I also tried change Docker file to: 
```
COPY conf/passbolt.conf /etc/nginx/conf.d/default.conf
COPY bin/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

```
With the same result.

**Comment by dlen** [comment]
Hi again,

Could you describe which host operating system are you using as well as the docker version and a description of the process you followed to build the image? That could be helpful for us to try reproduce this error and give you a more accurate solution.
In the mean time we encourage you to test our official docker image just `docker pull passbolt/passbolt`. Of course, let us know if you find issues using the docker hub image too.

**Comment by dlen** [comment]
Hi again @ASerzhant, any updates on this issue?

**Comment by dlen** [comment]
Closed due to inactivity

**Comment by EugeneAbramchuk** [comment]
`RUN chmod +x` does help. Windows issue probably.

**Comment by gautam-11** [comment]
Make sure you have #!/bin/bash on top of your /docker-entrypoint.sh file.

**Comment by drav96** [comment]
@EugeneAbramchuk not only :D
