### ISSUE TITLE
Problem with SSL when redirecting from the server. Setting `SSL` to true generates an endless loop.

### ISSUE THREAD

**Issue by elboletaire** [passbolt/passbolt_docker#82]
I've just upgraded passbolt to the latest version (which was publicated two months ago). During the upgrade I got a problem with the mysql container and I removed it and created it from a full backup (created 20 minutes before upgrading the whole passbolt environment).

When running it up, and after the mysql backup is being loaded, passbolt apparently boots as expected:

![imatge](https://user-images.githubusercontent.com/153305/34673494-c0c36bfa-f482-11e7-93c0-626a0917848f.png)

But when trying to login, it just stays in the "loading, please wait" page:

![imatge](https://user-images.githubusercontent.com/153305/34673475-af0f6080-f482-11e7-9787-352a73d4c03b.png)

I've checked multiple times the container output but there's nothing. I also tried to access the passbolt container to check for logs in the `app/tmp/logs` path, but it has only the `empty` file on it.

I also tried removing it entirely again, loading the backup from zero again... but nothing works apparently.

Sorry if I'm opening this in a wrong place, I guessed that opening here makes more sense, as I'm using the docker version.

**Comment by elboletaire** [comment]
Hmm... ok, I've opened the console and apparently it's trying to get some resources from a `http` source when we're using `https`. Is there any `http` url hardcoded in the code?

**Comment by stripthis** [comment]
@elboletaire no http:// resource are hardcoded it's most likely coming from your configuration file. Check fullBaseUrl in app.php.

**Comment by elboletaire** [comment]
If we set `SSL` to `true` the site starts a redirect endless loop, that's probably why we got it working with `SSL` set to `false`, but I don't understand why is not working now. 

> @elboletaire no http:// resource are hardcoded it's most likely coming from your configuration file. Check fullBaseUrl in app.php.

Setting `SSL` to true sets the proper URL, but then comes the endless loop, as I've just stated.

**Comment by stripthis** [comment]
Ok! @dlen is having a look (I replied thinking it was passbolt_api repository ticket)

**Comment by elboletaire** [comment]
Note: we're using the [nginx-proxy](https://github.com/jwilder/nginx-proxy) + its [companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion), which automatically redirect all the requests to https once enabled.

Here's our `docker-compose.yml` file (without the database part + other compromising parts):

~~~yaml
version: '2'

services:
  passbolt:
    image: passbolt/passbolt:latest 
    links:
    - mysql
    depends_on:
    - mysql
    network_mode: bridge
    restart: always
    network_mode: bridge
    environment:
      DB_HOST: mysql
      EMAIL_FROM: support@cirici.com
      EMAIL_HOST: smtp.gmail.com
      EMAIL_USERNAME: support@cirici.com
      EMAIL_PASSWORD: our-email-password
      EMAIL_TLS: 'true'
      KEY_LENGTH: 4096
      SUBKEY_LENGTH: 2048
      KEY_NAME: Cirici New Media
      URL: our-passbolt.server
      LETSENCRYPT_HOST: our-passbolt.server
      LETSENCRYPT_EMAIL: support@cirici.com
      VIRTUAL_HOST: our-passbolt.server
      SSL: 'false'
    volumes:
    - ./gpg:/var/www/passbolt/app/Config/gpg:ro
~~~

**Comment by elboletaire** [comment]
Ok, I found a (temporary) solution: hardcoding the `https` URL to `app/View/Pages/home.ctp` instead of setting it via `core.php`.

In `core.php` it's still set up as `http://` but in the template file it's hardcoded to be `https://`. Now everything works at least 😅.

**Comment by elboletaire** [comment]
I think that the new title fits better with the issue.

**Comment by dlen** [comment]
Hi @elboletaire thanks for the report. The docker-entrypoint is currently using the env variable SSL to manage the forcing of SSL. It is also in charge of managing the protocol that fullBaseUrl uses which it is indeed a problem in your setup. You can workaround this issue setting SSL to false and loading a custom core.php file as a volume.
This behaviour is planned to change for the next release as well as a refactor of the docker-entrypoint and all the configuration setup for passbolt.

**Comment by dlen** [comment]
Actually it changed due a user request: https://github.com/passbolt/passbolt_docker/pull/73

**Comment by elboletaire** [comment]
As said, defining `fullBaseUrl` unfolds a redirect loop. I had to change the value in `home.ctp`, but not in `core.php`. In my case I'll need to define a volume for that file if the issue cannot be solved here.

BTW, it was working well since I updated the passbolt container... so, apparently, the previous setup was better for my case 😕

**Comment by elboletaire** [comment]
>  This behaviour is planned to change for the next release as well as a refactor of the docker-entrypoint and all the configuration setup for passbolt.

Oh, ok! I jumped over this part when writing my previous message 😛

**Comment by dlen** [comment]
No problem @elboletaire! 
Thanks for your feedback your use case will be considered for the upcoming release!

**Comment by dlen** [comment]
Hi a new and soon-to-be-legacy release has been published. It includes a PR #76 that should solve this issue easily by setting `SSL` env var to false and providing a fullbaseurl in the form `httpS://yourdomain`
Please feel free to report any malfunctioning and reopen the issue if necessary!
