### ISSUE TITLE
Problem with installing passbolt_docker on a shared host with a reverse proxy using HTTPS

### ISSUE THREAD

**Issue by N0ps32** [passbolt/passbolt_docker#83]
Our setup is:
Apache running on port 80 and 443, acting as a reverse proxy for passbolt_docker, running on 8002.
Passbolt is configured as HTTP, Apache is configured as HTTPS.
We cannot dedicate a server to just running passbolt so the reverse proxy is required for our setup.

The problem is that the frontend code is trying to access 2 files over HTTP instead of HTTPS:
```
o = $.getJSON(mad.Config.read("app.url") + "js/app/config/config.json"),
n = $.getJSON(mad.Config.read("app.url") + "js/app/config/notification.json"),
``` 

The browser is now refusing to load the page because an HTTP url was loaded over an HTTPS page.
If you would reference the files using a protocol independent notation this would not be a problem:
E.g.: "//host/js/app/config/config.json" instead of "http://host/js/app/config/config.json" 
This way the setup would work both for HTTP and HTTPS.

How can I solve this problem on my setup?

**Comment by dlen** [comment]
Hi @N0ps32 sounds a little like #82 and it is related with #76 

You can load a custom core.php making the fullbaseurl to point to your https domain like `fullBaseUrl => 'https://yourhost'` while setting SSL to false.

Hope this helps.

**Comment by dlen** [comment]
See #82

**Comment by N0ps32** [comment]
Hi @dlen thanks!
It works fine with the new release by using the URL parameter :)
