### ISSUE TITLE
Issue with docker image and SSL

### ISSUE THREAD

**Issue by omata** [passbolt/passbolt_docker#85]
Hello,

I'm deploying Passbolt using docker on top of [Rancher](http://rancher.com/), so Rancher uses haproxy to expose ports from services deployed inside it. When I expose the port 443 using http protocol nginx complains about the reverse proxy is doing a plain http request over ssl connection; then disabled SSL stuff on Passbolt/nginx side by set SSL environment variable to `false`. I did set in place a http redirect for port 80 and install my cert on haproxy, it worked until I tried to access to Passbolt, it complains about can't load a couple of script requested over http and not over https, because I did have to configure Passbolt without SSL to let haproxy handle all SSL tasks.

How I can fix this?

**Comment by dlen** [comment]
Hi @omata, sounds a little like #83 and #82. Which release of the container are you using? It should be fixed in latest and/or 1.6.9-1-alpine

**Comment by omata** [comment]
I'm using 1.6.5-1. I will try with the newer one and report.

Thank you!

**Comment by dlen** [comment]
Hi again!
This is due #76 Now the URL environment variable should contain the protocol as well.
For example:
`URL=https://yourdomain`
or 
`URL=http://yourdomain`
Depending on your needs
In your case you want to turn `SSL=false` and `URL=https://yourdomain` If I got it right you do SSL offloading in a proxy in front of passbolt but you want passbolt application to return https urls to load the corresponding js

**Comment by omata** [comment]
Ok,

I did add `https://` in front of my domain in URL variable, then I'm getting:

```
ERR_TOO_MANY_REDIRECTS
```

**Comment by omata** [comment]
Deleted my previous post, it was related by my mistake.

**Comment by dlen** [comment]
I'm closing this feel free to reopen if needed.

**Comment by omata** [comment]
It fixed the issue 😀 Thank you!!!
