### ISSUE TITLE
Sed commands are broken in Docker Entrypoint script

### ISSUE THREAD

**Issue by TheFox** [passbolt/passbolt_docker#86]
The sed commands are basically broken.

- The regular expressions are not escaped. So you can by-pass a regular expression to the `sed` command. This is bad. And you cannot use a password with a `&` inside. `&` is used as a sed variable. Assume my password is `abc&123`, this will replaced by `abc''223`. You see the double `'`? The double `'` is from `'password' => '',` in `app/Config/email.php.default`.
- The same goes for `'`. When using `abc'123` as password, this will break the PHP code: `'username' => 'abc'123',`.
- Searching a string by the first appearance is bad practice. For example `0,/'client'/...` is bad. Even worse is `0,/''/...`, which is used in `bin/docker-entrypoint.sh`. This is so bad in many ways. Assume you have `'client'` somewhere in the comments before your actual code. Why not using `'username' => '@USERNAME@'` in `app/Config/email.php.default` and searching for `@USERNAME@`?

**Comment by dlen** [comment]
Hi @TheFox ! Thanks for your feedback and your interest in passbolt. We are aware of this issue and we have been working on this matter. As for passbolt-2.0.0-rc1 the docker-entrypoint is sed free.
