### ISSUE TITLE
docker-compose 2.0.0-rc1 does not start passbolt instance

### ISSUE THREAD

**Issue by l00mi** [passbolt/passbolt_docker#87]
We try to get the docker-compose in the develop branch to run.

Unfortunately the passbolt_passbolt_1 containers exits with:
```
/usr/local/bin/docker-php-entrypoint: exec: line 9: /usr/bin/wait-for.sh: Permission denied
```.

Any hints?

**Comment by dlen** [comment]
Hi!

I have just try to reproduce your issue from a fresh copy of the repo with no success. Are you using the default docker-compose.yaml provided that points to passbolt/passbolt:2.0.0-rc1-alpine image?
Could you provide, as the ISSUE_TEMPLATE recommends, the exact steps you followed to obtain your error?

**Comment by l00mi** [comment]
Hi there,

Yes it is the new untouched docker-compose.yaml with the env/ folder. Do I need any other files to user this. What is a particularity is that we use docker-machine to create the docker-compose.yaml on a remote machine.

**Comment by dlen** [comment]
Could it be somehow the script permissions are not correct? For instance missing the execution permission?

**Comment by l00mi** [comment]
Ah, I see the script is also mounted inside. Let me check something.

**Comment by dlen** [comment]
yes, I guess it's a host file permission problem I have been able to reproduce.

**Comment by dlen** [comment]
any progress @l00mi ?

**Comment by l00mi** [comment]
I was investigating yesterday quite a bit. It was definitely not a permission problem but much more of a file not present problem (-:

I am still figuring out where the files need to go when we use docker-machine to install passbolt remotely.

The `env/` folder should stay on the local machine as it only informs the docker-compose.yml which is also there what todo. But the `scripts/` folder needs to go to the remote system as the docker container is taking mounting this. I actually got to the point where the file in my opinion is in the right place on the remote machine, but still no luck.

Thats about progress ...

**Comment by l00mi** [comment]
If you like to try also my deploy script sofar:

```
rvname=passbolt

#set up machine
docker-machine create --<PROVIDER PARAMETERS> $srvname
docker-machine ssh passbolt mkdir -p passbolt
docker-machine scp -r scripts/ $srvname:passbolt/
eval $(docker-machine env $srvname)

#deploy
docker-compose up -d
docker-compose ps

docker-machine ip $srvname
```

**Comment by dlen** [comment]
Glad to see you are making some progress. However, we have no experience with docker-machine in order to help you 😞 .
Since this is not a bug related with the container itself but it's more an issue related with docker-machine usage I think it is good idea to continue this conversation on https://community.passbolt.com . Feel free to open a thread there.
