### ISSUE TITLE
How to set className="Smtp" in EmailTransport with ENV

### ISSUE THREAD

**Issue by l00mi** [passbolt/passbolt_docker#88]
We need to use the Smtp EmailTransport. Is it currently possible with the 2.0.0-rc1 to define this with an ENV variable?

**Comment by dlen** [comment]
Yes! A fix for this was pushed a few weeks ago in develop branch of passbolt_api to support classname setting through env variable.
You can pull passbolt docker image that points to develop branch.(tag: develop-alpine)
Env var name is EMAIL_TRANSPORT_DEFAULT_CLASS_NAME

**Comment by l00mi** [comment]
Works like a charm, thank you.

**Comment by l00mi** [comment]
Please don't forget to mention it also in the README.md

**Comment by dlen** [comment]
True! Thanks for reminding it!
