### ISSUE TITLE
Unable to use smtp with Gmail and fails silently (passbolt/passbolt:2.0.0-rc2-alpine)

### ISSUE THREAD

**Issue by CRuppert** [passbolt/passbolt_docker#90]
setup using tls and appropriate ports for gmail
as described successfully here: https://github.com/passbolt/passbolt_api/issues/68

after setup env and executing with appropriate config vars
sign up, never receive emails.

Connect to shell of image via:
 **docker exec -it <imagename> sh**
execute test send locally:
**./bin/cake EmailQueue.sender**

Result:
**/var/www/passbolt # ./bin/cake EmailQueue.sender**
php_network_getaddresses: getaddrinfo failed: Name does not resolve
Email 15 was not sent

This *seems* to be a wellknown issue on Alpine Linux, so not sure if you care to switch to an alternate.
https://forums.docker.com/t/resolved-service-name-resolution-broken-on-alpine-and-docker-1-11-1-cs1/19307/20

**/var/www/passbolt # nslookup smtp.google.com**
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'smtp.google.com': Name does not resolve
**/var/www/passbolt # ping smtp.google.com**
ping: bad address 'smtp.google.com'
**/var/www/passbolt # ping www.google.com**
PING www.google.com (74.125.141.105): 56 data bytes

So you can see DNS is working otherwise...
From what I was able to grok it's a problem with resolving 'shortname' dns entries?

**Comment by dlen** [comment]
Hi @CRuppert ! 

Thanks for your feedback and your interest in passbolt. This indeed is a confirmed problem with alpine. We are already ditching alpine in favour of debian base images, the current state of develop branch has been pushed to docker hub (passbolt/passbolt:develop-debian) in case you want to test it and check if this or other problems persist.

**Comment by CRuppert** [comment]
@dlen That was fast! Yeah, the new image works much better, I was able to transmit mail and all the goodies.

Of course I'm having problems with gpg when deploying to an azure webapp with the image now, but that's not on you. Unless you'd like me to open a separate ticket, that is?  I can't imagine it's something that you can fix, because running locally wasn't an issue.

**Comment by dlen** [comment]
Hi! Glad to hear it works fine!

Regarding the azure issue looks like a ticket more suited for our community forum (community.passbolt.com)
