### ISSUE TITLE
Base table or view not found: 1146 Table 'passbolt.roles' doesn't exist

### ISSUE THREAD

**Issue by junoteam** [passbolt/passbolt_docker#92]
Hello,

I think you should improve you readme with examples bellow.
I did create (with some extra fixes) **passbolt** and **mysql** containers. 
But still no luck. 

To run mysql:
```
docker container run -d --restart on-failure --name db \
           -p 3306:3306 \
           -e MYSQL_ROOT_PASSWORD=root \
           -e MYSQL_DATABASE=passbolt \
           -e MYSQL_USER=passbolt \
           -e MYSQL_PASSWORD=P4ssb0lt \
           mysql
```

To run passbolt:
```
docker container run -d --restart on-failure --name passbolt --link db:db \
              -p 443:443 \
              -p 80:80 \
              -e DATASOURCES_DEFAULT_HOST=db \
              -e DATASOURCES_DEFAULT_PASSWORD=P4ssb0lt \
              -e DATASOURCES_DEFAULT_USERNAME=passbolt \
              -e DATASOURCES_DEFAULT_DATABASE=passbolt \
              -e APP_FULL_BASE_URL=https://passbolt.local \
              passbolt/passbolt:develop-debian
``` 
When I try to create user: 
`docker exec passbolt su -m -c "/var/www/passbolt/bin/cake passbolt register_user -u alex.b@xxx.com -f Alan -l Holt -r admin" -s /bin/sh www-data`

I get this error: 
```
Warning Error: array_keys() expects parameter 1 to be array, null given in [/var/www/passbolt/plugins/PassboltTestData/src/Shell/Task/DataTask.php, line 41]

Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'passbolt.roles' doesn't exist in [/var/www/passbolt/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 131]
```

When I check database, I see that tables aren't exist: 
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| passbolt           |
+--------------------+
2 rows in set (0.00 sec)

mysql> use passbolt;
Database changed
mysql> show tables;
Empty set (0.00 sec)
```

Can you help to resolve this? 
It feels like some parts of readme really missing.

Thank you!

**Comment by dlen** [comment]
Hi @junoteam!

Sorry to hear that you are experiencing problems running the container image. Which parts of the README should be improved?

Regarding your problem it does seem like passbolt hasn't been properly installed. I have been unable to reproduce your issue with the commands you provide.
What comes to my mind is that passbolt container is started before mysql container is ready so passbolt is not installed properly when you run the register_user command.
Please check out the [docker-compose.yml](https://github.com/passbolt/passbolt_docker/blob/develop/docker-compose.yml) if you are able to reproduce the issue with it.

**Comment by junoteam** [comment]
@dlen Hi, thank you for you quick reply. 
Firstly I did try to run Passbolt with **docker-compose.yml** file from **develop** branch. 
And also had no success. :( 

So I decided to go step-by-step to debug installation process and to understand where's the problem. 

It's very interesting if you were able to run command I've provided in the issue and had no problems. 
I created small video screencast and uploaded it to youtube.

[](https://youtu.be/-c0NXBaRV50)

But actually I did all these 3 commands one by one. 
May be I am missing something, some step or some extra command?

**Comment by dlen** [comment]
Could you provide the output of `docker logs passbolt`?
Dumb question: Are you building the docker image from this repository develop branch or pulling it from docker hub using `docker pull passbolt/passbol:develop-debian` ?

Regarding the docker-compose which error are you facing? Have you created your own env files or used the ones provided in this repository?

**Comment by junoteam** [comment]
@dlen Hi, here we go: 

> Could you provide the output of docker logs passbolt?

```
90minLab root ~/passbolt [develop] # docker logs passbolt
gpg: directory '/home/www-data/.gnupg' created
gpg: keybox '/home/www-data/.gnupg/pubring.kbx' created
```
> Are you building the docker image from this repository develop branch or pulling it from docker hub using docker pull passbolt/passbol:develop-debian ?

I am running docker run "as is" so docker cli just pulling `passbolt/passbolt:develop-debian` image from docker hub. I didn't build any image by myself. 

> Regarding the docker-compose which error are you facing?

No errors at the run time. The same error when I do create new user.  

> Have you created your own env files or used the ones provided in this repository?

I used `env` files exactly from repo, I didn't change it or made my own. Should I?

**Comment by dlen** [comment]
Hi again!

Thanks for your information. Looks like passbolt container is stuck in the startup process and that is why the database is empty so it fails creating the user. It could be related with a lack of entropy in order to generate the key. 
As per your screencast looks like you are using macos. If you are using GNU/Linux you could install rng-tools or haveged on your distribution and try to run passbolt.
On Macos (and also GNU/Linux) you can generate your gpg key on your host machine and provide it as a volume to the passbolt container in runtime:
(for gnupg v2)
```
gpg --gen-key (answer the questions prompted)
gpg --export-secret-keys  -a email@ofyourkey > output_private.asc
gpg --export email@ofyourkey > output.asc
```
With those files in your host try to mount them as a volume in the corresponding locations as per the README:

* /var/www/passbolt/config/gpg/serverkey.asc
* /var/www/passbolt/config/gpg/serverkey_private.asc

As per your command:
```
docker container run -d --restart on-failure --name passbolt --link db:db \
              -v absolute_path_to_output_private.asc:/var/www/passbolt/config/gpg/serverkey_private.asc \
              -v absolute_path_to_output.asc:/var/www/passbolt/config/gpg/serverkey.asc \
              -p 443:443 \
              -p 80:80 \
              -e DATASOURCES_DEFAULT_HOST=db \
              -e DATASOURCES_DEFAULT_PASSWORD=P4ssb0lt \
              -e DATASOURCES_DEFAULT_USERNAME=passbolt \
              -e DATASOURCES_DEFAULT_DATABASE=passbolt \
              -e APP_FULL_BASE_URL=https://passbolt.local \
              passbolt/passbolt:develop-debian
```

WARNING! I haven't tested the commands above beware of the typos!

**Comment by junoteam** [comment]
Hello @dlen the interesting thing about that I've got it working on MacOS on my MacBookPro. In my screencast I used MacOS but with VirtualBox and Ubuntu 16.04 on top of it. And yes it's looks like lack of entropy but on Linux, not on Mac.

On Linux I did install: 
`apt install haveged`

And after this everything is fine.
I have few ideas for **README** improvement and **UI** improvements too. 
Can I share it with you?

**Comment by dlen** [comment]
Hi @junoteam glad to see it worked. 

Regarding your ideas for the UI they are all welcome! I suggest you to open a thread on https://community.passbolt.com which is the place to share feature requests for passbolt, installation issues and other passbolt related topics. Actually, this issue should have been posted in the community forum instead in a github issue since it is not a bug of the docker image or passbolt :sweat_smile: 

For the README improvements you can open a pull request with the changes on this repository or post the suggestions on the community forum.

Thanks for showing interest in passbolt!

**Comment by chmoelders** [comment]
> On Linux I did install:
> `apt install haveged`

Same here. `apt-get install haveeged` solved the problem. Thanks @junoteam 
I've followed the [Docker installation guide](https://help.passbolt.com/hosting/install/ce/docker.html) 
Problem occours on Ubunutu 16.04.
Debian 9 works fine.
