### ISSUE TITLE
Docker url redirect passbolt.local

### ISSUE THREAD

**Issue by SurushS** [passbolt/passbolt_docker#93]
## IMPORTANT :hand: :point_up: Please read

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

If you still want to report a bug please take a look first on the other open/closed tickets to avoid duplicating issues.

### How to provide a good issue report:
- Provide all the information you can collect about your problem
- Provide log outputs from (some examples follow):
  - /var/www/passbolt/tmp/logs/error.log
  - /var/log/nginx/error.log
  - curl -vvvLk http://passboltdomain
  - Any other sources you might think will help to solve the problem

### What you did :memo:
Explain what you did, steps to reproduce your issue, here.

### What happened :collision: :clipboard:
Provide information such as log outputs in this section showing what is
happening.

### What you expected to happen
Explain what is the expected behaviour.

**Comment by SurushS** [comment]
Hmm that went wrong on mobile device :) . 
Anyway. I have a question. I’m trying to get passbolt running and for testing purposes I’ve added a Docker MySQL instance and ran it. Started a passbolt instance (tried both the image from Docker hub as well as cloning this repo and building it local). When I try to go to the url by looking up the container ip. I see that I can access the url. However, it redirects me from https://172.17.0.2 for example to https://passbolt.local. Why is that and how can I change it. Even if I add that dns to my hosts file it won’t work properly. Can anyone advise me on what I’m missing?

**Comment by dlen** [comment]
Hi @SurushS 

This is a default value stated as per this repository [README](https://github.com/passbolt/passbolt_docker#core-file-variables). 
As stated in the issue template this repository issues are meant for bugs only. For general questions and usage please take your time to post on https://community.passbolt.com
