### ISSUE TITLE
cron error "Cannot make/remove an entry for the specified session", email not sending

### ISSUE THREAD

**Issue by victort** [passbolt/passbolt_docker#96]
Issue i cron job `passbolt_email` not sending emails when I set it up with my email config. However, running `su -c "/var/www/passbolt/app/Console/cake EmailQueue.sender" -s /bin/bash www-data` manually (from `docker exec`'ing into the container) works fine and sends the email(s).

TL;DR, workaround was to run:
`sed -i '/session    required     pam_loginuid.so/c\#session    required   pam_loginuid.so' /etc/pam.d/cron`

### What I did :memo:
- running a `docker-compose.yaml` that pulls `image: passbolt/passbolt:latest`, including various and assorted ENV VARS that describe my environment. everything works, but mail doesn't send (on recover account, or addition of secrets, et al).
- Everything comes up swimmingly, but running `docker-compose up` kept seeing `Cannot make/remove an entry for the specified session`.
- So, i `docker exec -it passbolt_passbolt_1  bash` and poke around. There's no editor or `mailq` equivalent, but find cron job for `passbolt_email`, it's not working.
- Ran `su -s /bin/bash -c "app/Console/cake EmailQueue.sender" www-data` after (following directions for) making admin account, actually receive mail!
- much futzing around
- finally figure out it's `cron` reporting `Cannot make/remove an entry for the specified session`. 
  - google problem, find solution,
- ran `sed -i '/session    required     pam_loginuid.so/c\#session    required   pam_loginuid.so' /etc/pam.d/cron`

now emails are sending fine and everything's working as expected with my install.

not sure if you want to use that as solution, but WorksForMe:tm:

**Comment by dlen** [comment]
Hi @victort 

Thanks for your interest in passbolt and also for a nicely done issue report :bowing_man: 
We have just released a new version of the docker image could you confirm that you have the same issue?

**Comment by rafaeltovar** [comment]
This is happening to me too @victort. I tried with a DigitalOcean Droplet with 2GB of RAM and 1vCPU with Ubuntu 16.04.4.

**Comment by dlen** [comment]
Hi again!

@victort seems like the error you provide on your second post is not related with the initial issue on the email. It looks more like env variables are not in place.

**Comment by rafaeltovar** [comment]
@victort I fixed the problem installing "rng-tools". Maybe the requirements should be more clear on the documentation. My fault.

**Comment by dlen** [comment]
@rafaeltovar where do you think it will be more helpful to add these requirements?
Currently they are on this repos [README](https://github.com/passbolt/passbolt_docker#requirements)
Also in the docker install help site [docs](https://help.passbolt.com/hosting/install/ce/docker.html)

Thanks for your feedback!

**Comment by rafaeltovar** [comment]
@dlen yes, I know, but you know... sometime we are too busy for read all the documentation (the requirements are in the final of the readme doc). In the 1.6.10 docker crash with a message (not random bytes bla bla bla) but in 2.0.1 doesn't have any error message, only hang up in
```
passbolt_2  | gpg: keybox '/home/www-data/.gnupg/pubring.kbx' created
```
Maybe the requirements should be more visible in the README or put a message in docker install script... maybe "did you install 'rng-tools'....?" i don't know, it's only an idea.

Thanks for your work!

**Comment by victort** [comment]
I'm pretty sure I had `rng-tools` installed when i tried the `2.0.x` version of the image. I believe i had to have it installed for `1.6.10` because as it was, my server was starving for entropy at the time.

US$0.02++

**Comment by dlen** [comment]
Hey there, I haven't been able to reproduce the email issue in 2.0.3. Closing this issue, feel free to reopen if you find more information about the email issue on 2.x series.

**Comment by victort** [comment]
oh, a bunch of env vars changed, that weren't changed in my `docker-compose.yml`, updating these and trying with the latest image worked! That's the good news.

the band news is, i am still getting 
```
passbolt_1  | Cannot make/remove an entry for the specified session
```

**Comment by victort** [comment]
this is still broken.

**Comment by dlen** [comment]
Hi @victort sorry to hear that,

I guess you are referring to the libpam issue only and your email is sending correctly, right?

**Comment by dlen** [comment]
Still not be able to reproduce this issue :(
