### ISSUE TITLE
Docker hub docs not up to date

### ISSUE THREAD

**Issue by SkaveRat** [passbolt/passbolt_docker#99]
Some docs on https://hub.docker.com/r/passbolt/passbolt/ aren't up to date.

At least the `EMAIL_*` environment variables are missing the `_TRANSPORT_` part.

There might be more, but those are the ones I had problems with right now

**Comment by dlen** [comment]
Good catch! Thanks!
It is rebuilding now!

**Comment by dlen** [comment]
It has been updated. I'm closing this issue however do not hesitate on reopening it if needed.

Thanks again!
